<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>$(CaseName)</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(FixtureDir)/*.cs" />
    <Compile Include="$(ProductionDir)/*.cs" />
    <Reference Include="$(UnityManaged)/UnityEngine/*.dll" />
  </ItemGroup>
</Project>
