/* Host-only proof harness: executes unchanged Unity-cooked SPIR-V. Not in APK.
 * Input is a bounded text fixture generated by host_vulkan.py. Vulkan 1.0 only.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vulkan/vulkan.h>
#define MAX_R 64
#define CHECK(call)                                                            \
  do {                                                                         \
    VkResult proof_result = (call);                                            \
    if (proof_result != VK_SUCCESS) {                                          \
      fprintf(stderr, "%s failed: %d\n", #call, proof_result);                 \
      exit(2);                                                                 \
    }                                                                          \
  } while (0)
static VkPhysicalDevice physical;
static VkDevice device;
static VkPhysicalDeviceMemoryProperties memory;
static uint32_t memtype(uint32_t mask, VkMemoryPropertyFlags flags) {
  for (uint32_t i = 0; i < memory.memoryTypeCount; i++)
    if ((mask & (1u << i)) &&
        (memory.memoryTypes[i].propertyFlags & flags) == flags)
      return i;
  fprintf(stderr, "memory type missing\n");
  exit(2);
}
static void load(const char *path, void *data, size_t bytes) {
  FILE *f = fopen(path, "rb");
  if (!f || fread(data, 1, bytes, f) != bytes) {
    fprintf(stderr, "fixture read failed: %s\n", path);
    exit(2);
  }
  fclose(f);
}
static void save(const char *path, void *data, size_t bytes) {
  FILE *f = fopen(path, "wb");
  if (!f || fwrite(data, 1, bytes, f) != bytes) {
    fprintf(stderr, "fixture write failed\n");
    exit(2);
  }
  fclose(f);
}
static VkBuffer buffer(VkDeviceSize bytes, VkDeviceMemory *allocation) {
  VkBuffer b;
  VkBufferCreateInfo info = {.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                             .size = bytes,
                             .usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT |
                                      VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                      VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
                                      VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                             .sharingMode = VK_SHARING_MODE_EXCLUSIVE};
  CHECK(vkCreateBuffer(device, &info, NULL, &b));
  VkMemoryRequirements req;
  vkGetBufferMemoryRequirements(device, b, &req);
  VkMemoryAllocateInfo ai = {
      .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
      .allocationSize = req.size,
      .memoryTypeIndex = memtype(req.memoryTypeBits,
                                 VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                     VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)};
  CHECK(vkAllocateMemory(device, &ai, NULL, allocation));
  CHECK(vkBindBufferMemory(device, b, *allocation, 0));
  return b;
}
typedef struct {
  uint32_t set, binding, kind, format, dimension, w, h, d, layers, bytes;
  char path[1024];
  VkBuffer buf;
  VkDeviceMemory alloc;
  VkImage image;
  VkDeviceMemory imem;
  VkImageView view;
  VkSampler sampler;
  VkDescriptorBufferInfo bi;
  VkDescriptorImageInfo ii;
} Resource;
static void barrier(VkCommandBuffer command, Resource *r, VkImageLayout old,
                    VkImageLayout next, VkAccessFlags src, VkAccessFlags dst,
                    VkPipelineStageFlags s, VkPipelineStageFlags d) {
  VkImageMemoryBarrier b = {
      .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
      .srcAccessMask = src,
      .dstAccessMask = dst,
      .oldLayout = old,
      .newLayout = next,
      .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
      .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
      .image = r->image,
      .subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, r->layers}};
  vkCmdPipelineBarrier(command, s, d, 0, 0, NULL, 0, NULL, 1, &b);
}
int main(int argc, char **argv) {
  if (argc != 2)
    return 2;
  FILE *f = fopen(argv[1], "r");
  if (!f)
    return 2;
  char spv[1024];
  uint32_t bytes, n, gx, gy, gz;
  if (fscanf(f, "%1023s %u %u %u %u %u", spv, &bytes, &n, &gx, &gy, &gz) != 6 ||
      n > MAX_R || bytes % 4)
    return 2;
  Resource resources[MAX_R] = {0};
  for (uint32_t i = 0; i < n; i++) {
    Resource *r = &resources[i];
    if (fscanf(f, "%u %u %u %u %u %u %u %u %u %u %1023s", &r->set, &r->binding,
               &r->kind, &r->format, &r->dimension, &r->w, &r->h, &r->d,
               &r->layers, &r->bytes, r->path) != 11 ||
        r->set > 3)
      return 2;
  }
  fclose(f);
  VkApplicationInfo app = {.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
                           .pApplicationName = "Quest original compute proof",
                           .apiVersion = VK_API_VERSION_1_0};
  VkInstanceCreateInfo ici = {.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
                              .pApplicationInfo = &app};
  VkInstance instance;
  CHECK(vkCreateInstance(&ici, NULL, &instance));
  uint32_t pc = 0;
  CHECK(vkEnumeratePhysicalDevices(instance, &pc, NULL));
  if (!pc)
    return 2;
  VkPhysicalDevice *p = calloc(pc, sizeof(*p));
  CHECK(vkEnumeratePhysicalDevices(instance, &pc, p));
  physical = p[0];
  free(p);
  VkPhysicalDeviceProperties properties;
  vkGetPhysicalDeviceProperties(physical, &properties);
  vkGetPhysicalDeviceMemoryProperties(physical, &memory);
  uint32_t qc = 0;
  vkGetPhysicalDeviceQueueFamilyProperties(physical, &qc, NULL);
  VkQueueFamilyProperties *q = calloc(qc, sizeof(*q));
  vkGetPhysicalDeviceQueueFamilyProperties(physical, &qc, q);
  uint32_t family = 0;
  while (family < qc && !(q[family].queueFlags & VK_QUEUE_COMPUTE_BIT))
    family++;
  free(q);
  if (family == qc)
    return 2;
  float priority = 1;
  VkDeviceQueueCreateInfo qi = {.sType =
                                    VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
                                .queueFamilyIndex = family,
                                .queueCount = 1,
                                .pQueuePriorities = &priority};
  VkPhysicalDeviceFeatures features;
  vkGetPhysicalDeviceFeatures(physical, &features);
  VkPhysicalDeviceFeatures enabled = {
      .shaderStorageImageExtendedFormats =
          features.shaderStorageImageExtendedFormats};
  if (!enabled.shaderStorageImageExtendedFormats) {
    fprintf(stderr, "native extended storage formats missing\n");
    return 2;
  }
  VkDeviceCreateInfo di = {.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
                           .queueCreateInfoCount = 1,
                           .pQueueCreateInfos = &qi,
                           .pEnabledFeatures = &enabled};
  CHECK(vkCreateDevice(physical, &di, NULL, &device));
  VkQueue queue;
  vkGetDeviceQueue(device, family, 0, &queue);
  VkDescriptorSetLayoutBinding bindings[4][MAX_R] = {0};
  uint32_t counts[4] = {0}, setcount = 0;
  VkDescriptorType types[] = {
      VK_DESCRIPTOR_TYPE_SAMPLER, VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
      VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
      VK_DESCRIPTOR_TYPE_STORAGE_BUFFER};
  for (uint32_t i = 0; i < n; i++) {
    Resource *r = &resources[i];
    if (r->kind > 4)
      return 2;
    bindings[r->set][counts[r->set]++] = (VkDescriptorSetLayoutBinding){
        .binding = r->binding,
        .descriptorType = types[r->kind],
        .descriptorCount = 1,
        .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT};
    if (r->set + 1 > setcount)
      setcount = r->set + 1;
  }
  VkDescriptorSetLayout layouts[4];
  for (uint32_t i = 0; i < setcount; i++) {
    VkDescriptorSetLayoutCreateInfo li = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = counts[i],
        .pBindings = bindings[i]};
    CHECK(vkCreateDescriptorSetLayout(device, &li, NULL, &layouts[i]));
  }
  VkPipelineLayout pipelineLayout;
  VkPipelineLayoutCreateInfo pli = {
      .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
      .setLayoutCount = setcount,
      .pSetLayouts = layouts};
  CHECK(vkCreatePipelineLayout(device, &pli, NULL, &pipelineLayout));
  uint32_t *code = malloc(bytes);
  load(spv, code, bytes);
  VkShaderModule module;
  VkShaderModuleCreateInfo sm = {
      .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
      .codeSize = bytes,
      .pCode = code};
  CHECK(vkCreateShaderModule(device, &sm, NULL, &module));
  free(code);
  VkComputePipelineCreateInfo pi = {
      .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
      .stage = {.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                .stage = VK_SHADER_STAGE_COMPUTE_BIT,
                .module = module,
                .pName = "main"},
      .layout = pipelineLayout};
  VkPipeline pipeline;
  CHECK(vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &pi, NULL,
                                 &pipeline));
  if (gx) {
    VkDescriptorPoolSize sizes[5];
    for (uint32_t i = 0; i < 5; i++)
      sizes[i] = (VkDescriptorPoolSize){types[i], MAX_R};
    VkDescriptorPool pool;
    VkDescriptorPoolCreateInfo pci = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        .maxSets = 4,
        .poolSizeCount = 5,
        .pPoolSizes = sizes};
    CHECK(vkCreateDescriptorPool(device, &pci, NULL, &pool));
    VkDescriptorSet sets[4];
    VkDescriptorSetAllocateInfo sa = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .descriptorPool = pool,
        .descriptorSetCount = setcount,
        .pSetLayouts = layouts};
    CHECK(vkAllocateDescriptorSets(device, &sa, sets));
    VkWriteDescriptorSet writes[MAX_R] = {0};
    for (uint32_t i = 0; i < n; i++) {
      Resource *r = &resources[i];
      writes[i] = (VkWriteDescriptorSet){
          .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
          .dstSet = sets[r->set],
          .dstBinding = r->binding,
          .descriptorCount = 1,
          .descriptorType = types[r->kind]};
      if (r->kind == 0) {
        VkSamplerCreateInfo si = {
            .sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
            .magFilter = VK_FILTER_NEAREST,
            .minFilter = VK_FILTER_NEAREST,
            .mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST,
            .addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
            .addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
            .addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
            .maxLod = 0};
        CHECK(vkCreateSampler(device, &si, NULL, &r->sampler));
        r->ii.sampler = r->sampler;
        writes[i].pImageInfo = &r->ii;
        continue;
      }
      r->buf = buffer(r->bytes, &r->alloc);
      void *data;
      CHECK(vkMapMemory(device, r->alloc, 0, r->bytes, 0, &data));
      load(r->path, data, r->bytes);
      vkUnmapMemory(device, r->alloc);
      if (r->kind >= 3) {
        r->bi = (VkDescriptorBufferInfo){r->buf, 0, r->bytes};
        writes[i].pBufferInfo = &r->bi;
        continue;
      }
      VkFormatProperties fp;
      vkGetPhysicalDeviceFormatProperties(physical, r->format, &fp);
      VkFormatFeatureFlags required = r->kind == 2
                                          ? VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT
                                          : VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT;
      if (!(fp.optimalTilingFeatures & required)) {
        fprintf(stderr, "native format unsupported: %u\n", r->format);
        return 2;
      }
      VkImageCreateInfo ii = {
          .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
          .imageType = r->dimension == 3 ? VK_IMAGE_TYPE_3D : VK_IMAGE_TYPE_2D,
          .format = r->format,
          .extent = {r->w, r->h, r->d},
          .mipLevels = 1,
          .arrayLayers = r->layers,
          .samples = VK_SAMPLE_COUNT_1_BIT,
          .tiling = VK_IMAGE_TILING_OPTIMAL,
          .usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_STORAGE_BIT |
                   VK_IMAGE_USAGE_TRANSFER_SRC_BIT |
                   VK_IMAGE_USAGE_TRANSFER_DST_BIT,
          .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
          .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED};
      CHECK(vkCreateImage(device, &ii, NULL, &r->image));
      VkMemoryRequirements mr;
      vkGetImageMemoryRequirements(device, r->image, &mr);
      VkMemoryAllocateInfo ma = {
          .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
          .allocationSize = mr.size,
          .memoryTypeIndex = memtype(mr.memoryTypeBits, 0)};
      CHECK(vkAllocateMemory(device, &ma, NULL, &r->imem));
      CHECK(vkBindImageMemory(device, r->image, r->imem, 0));
      VkImageViewCreateInfo vi = {
          .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
          .image = r->image,
          .viewType = r->dimension == 3
                          ? VK_IMAGE_VIEW_TYPE_3D
                          : r->dimension == 5 ? VK_IMAGE_VIEW_TYPE_2D_ARRAY
                                              : VK_IMAGE_VIEW_TYPE_2D,
          .format = r->format,
          .subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, r->layers}};
      CHECK(vkCreateImageView(device, &vi, NULL, &r->view));
      r->ii = (VkDescriptorImageInfo){.imageView = r->view,
                                      .imageLayout = VK_IMAGE_LAYOUT_GENERAL};
      writes[i].pImageInfo = &r->ii;
    }
    vkUpdateDescriptorSets(device, n, writes, 0, NULL);
    VkCommandPool cp;
    VkCommandPoolCreateInfo cpi = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
        .queueFamilyIndex = family};
    CHECK(vkCreateCommandPool(device, &cpi, NULL, &cp));
    VkCommandBuffer command;
    VkCommandBufferAllocateInfo cai = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool = cp,
        .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = 1};
    CHECK(vkAllocateCommandBuffers(device, &cai, &command));
    VkCommandBufferBeginInfo begin = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    CHECK(vkBeginCommandBuffer(command, &begin));
    for (uint32_t i = 0; i < n; i++) {
      Resource *r = &resources[i];
      if (r->kind != 1 && r->kind != 2)
        continue;
      barrier(command, r, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL, 0,
              VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
              VK_PIPELINE_STAGE_TRANSFER_BIT);
      VkBufferImageCopy region = {
          .imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, r->layers},
          .imageExtent = {r->w, r->h, r->d}};
      vkCmdCopyBufferToImage(command, r->buf, r->image, VK_IMAGE_LAYOUT_GENERAL,
                             1, &region);
      barrier(command, r, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_GENERAL,
              VK_ACCESS_TRANSFER_WRITE_BIT,
              VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT,
              VK_PIPELINE_STAGE_TRANSFER_BIT,
              VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);
    }
    vkCmdBindPipeline(command, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
    vkCmdBindDescriptorSets(command, VK_PIPELINE_BIND_POINT_COMPUTE,
                            pipelineLayout, 0, setcount, sets, 0, NULL);
    vkCmdDispatch(command, gx, gy, gz);
    VkMemoryBarrier mb = {.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER,
                          .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
                          .dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT |
                                           VK_ACCESS_HOST_READ_BIT};
    vkCmdPipelineBarrier(command, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                         VK_PIPELINE_STAGE_TRANSFER_BIT |
                             VK_PIPELINE_STAGE_HOST_BIT,
                         0, 1, &mb, 0, NULL, 0, NULL);
    for (uint32_t i = 0; i < n; i++) {
      Resource *r = &resources[i];
      if (r->kind != 2)
        continue;
      VkBufferImageCopy region = {
          .imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, r->layers},
          .imageExtent = {r->w, r->h, r->d}};
      vkCmdCopyImageToBuffer(command, r->image, VK_IMAGE_LAYOUT_GENERAL, r->buf,
                             1, &region);
    }
    VkMemoryBarrier host = {.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER,
                            .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
                            .dstAccessMask = VK_ACCESS_HOST_READ_BIT};
    vkCmdPipelineBarrier(command, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_HOST_BIT, 0, 1, &host, 0, NULL, 0,
                         NULL);
    CHECK(vkEndCommandBuffer(command));
    VkSubmitInfo submit = {.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
                           .commandBufferCount = 1,
                           .pCommandBuffers = &command};
    CHECK(vkQueueSubmit(queue, 1, &submit, VK_NULL_HANDLE));
    CHECK(vkQueueWaitIdle(queue));
    for (uint32_t i = 0; i < n; i++) {
      Resource *r = &resources[i];
      if (r->kind != 2 && r->kind != 4)
        continue;
      void *data;
      CHECK(vkMapMemory(device, r->alloc, 0, r->bytes, 0, &data));
      char output[1100];
      snprintf(output, sizeof(output), "%s.out", r->path);
      save(output, data, r->bytes);
      vkUnmapMemory(device, r->alloc);
    }
    // Each invocation is a short-lived proof process; destroy all Vulkan
    // objects.
    vkDestroyCommandPool(device, cp, NULL);
    vkDestroyDescriptorPool(device, pool, NULL);
    for (uint32_t i = 0; i < n; i++) {
      Resource *r = &resources[i];
      if (r->sampler)
        vkDestroySampler(device, r->sampler, NULL);
      if (r->view)
        vkDestroyImageView(device, r->view, NULL);
      if (r->image)
        vkDestroyImage(device, r->image, NULL);
      if (r->imem)
        vkFreeMemory(device, r->imem, NULL);
      if (r->buf)
        vkDestroyBuffer(device, r->buf, NULL);
      if (r->alloc)
        vkFreeMemory(device, r->alloc, NULL);
    }
  }
  // Original allocation formats, including the MSAA variants. This is host
  // format support, never a replacement for the game's actual device gates.
  const VkFormat nativeFormats[] = {VK_FORMAT_R32_SFLOAT,
                                    VK_FORMAT_R16_SFLOAT,
                                    VK_FORMAT_R32G32_SFLOAT,
                                    VK_FORMAT_R16G16_SFLOAT,
                                    VK_FORMAT_R8_UNORM,
                                    VK_FORMAT_R8G8_UNORM,
                                    VK_FORMAT_R16G16B16A16_SFLOAT,
                                    VK_FORMAT_R32G32B32A32_SFLOAT};
  int allNativeFormats = 1;
  for (uint32_t i = 0; i < 8; i++) {
    VkFormatProperties fp;
    vkGetPhysicalDeviceFormatProperties(physical, nativeFormats[i], &fp);
    if (!(fp.optimalTilingFeatures & VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT))
      allNativeFormats = 0;
  }
  printf("{\"device\":\"%s\",\"pipelineCreated\":true,\"dispatched\":%s,"
         "\"storageImageExtendedFormats\":true,\"robustBufferAccessEnabled\":"
         "false,\"allEightOriginalFormatsSupportStorageImages\":%s}\n",
         properties.deviceName, gx ? "true" : "false",
         allNativeFormats ? "true" : "false");
  vkDestroyPipeline(device, pipeline, NULL);
  vkDestroyShaderModule(device, module, NULL);
  vkDestroyPipelineLayout(device, pipelineLayout, NULL);
  for (uint32_t i = 0; i < setcount; i++)
    vkDestroyDescriptorSetLayout(device, layouts[i], NULL);
  vkDestroyDevice(device, NULL);
  vkDestroyInstance(instance, NULL);
  return 0;
}
