<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>$(CaseName)</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>CS8600;CS8602;CS8604;CS8625</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Boundaries.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="../../src/GloomhavenVR/WorldUI/TownServices/TownServiceMerchantTransaction.cs" />
    <Reference Include="$(UnityManaged)/UnityEngine/*.dll" />
    <Reference Include="UnityEngine.UI"><HintPath>$(UnityUi)</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
