using System.Collections;
using GloomhavenVR.Cards;
using static ScenarioRuleLibrary.CBaseCard;
static class Program {
 static int count;
 static void Check(bool ok,string message){count++;if(!ok)throw new Exception(message);}
 static (CardEffects,ScenarioRuleLibrary.CAbilityCard) Make(ECardPile pile){var card=new ScenarioRuleLibrary.CAbilityCard{CurrentCardPile=pile};var fx=new CardEffects();fx.Full.AbilityCard=card;return(fx,card);}
 sealed class NativeProbe:IEnumerator {internal bool Throw;internal readonly InvalidOperationException Error=new();public object Current=>this;public bool MoveNext(){if(Throw)throw Error;return true;}public void Reset(){}}
 static void Main(){
  foreach(var origin in new[]{ECardPile.Discarded,ECardPile.Round,ECardPile.Activated,ECardPile.Hand}){
   var(fx,card)=Make(origin);fx.ToggleEffect(true,CardEffects.FXTask.BurnCard);var live=fx.Live;var paint=fx.Paint;card.CurrentCardPile=ECardPile.Lost;
   for(int i=0;i<100;i++){
    fx.ToggleEffect(true,CardEffects.FXTask.LostMode);fx.ToggleAdditiveEffect(true,CardEffects.FXTask.BurnCard);fx.ToggleEffect(false,CardEffects.FXTask.LostMode);fx.RestoreCard();
    Check(fx.Starts==1&&fx.Resets==1&&ReferenceEquals(live,fx.Live)&&fx.Paint==paint,"Repeated native refresh must retain the first burn iterator and paint");
   }
   Check(fx.toggledEffects.Contains(CardEffects.FXTask.BurnCard)&&fx.toggledEffects.Contains(CardEffects.FXTask.LostMode),"Native burn task aliases must remain latched");
   var unused=fx.BurnCardTimeline(true);Check(ReferenceEquals(BurnArtwork.BurnTimelines.GetValue(fx,_=>throw new Exception()),live),"Unstarted iterators must not replace live playback tracking");
   while(live!.MoveNext()){Check(fx.Paint>=paint,"Native progress cannot reverse");paint=fx.Paint;}
   fx.ToggleEffect(true,CardEffects.FXTask.LostMode);fx.RestoreCard();Check(fx.Starts==1&&fx.Paint>=1,"Completed lost burns must never replay or turn blue");
   card.CurrentCardPile=ECardPile.Hand;fx.RestoreCard();Check(fx.Paint==0&&fx.Resets==2,"Actual model recovery must restore normal artwork");
   fx.ToggleEffect(true,CardEffects.FXTask.BurnCard);Check(fx.Starts==2,"Recovered cards may start a genuinely new burn");
   BurnArtwork.RetireBurnPlayback(fx);fx.RestoreCard();Check(fx.Paint==0,"Explicit pool retirement must allow reset even for old lost widgets");
  }
  var(bail,bc)=Make(ECardPile.Lost);bail.Disabled=true;bail.ToggleEffect(true,CardEffects.FXTask.BurnCard);bail.Disabled=false;bail.ToggleEffect(true,CardEffects.FXTask.BurnCard);Check(bail.Starts==1,"Synchronous native bail must allow a real first playback later");
  var(changed,cc)=Make(ECardPile.Lost);changed.ToggleEffect(true,CardEffects.FXTask.BurnCard);changed.Full.AbilityCard=new(){CurrentCardPile=ECardPile.Lost};changed.ToggleEffect(true,CardEffects.FXTask.LostMode);Check(changed.Starts==2,"Recycled widget identity must not inherit another card's burn");
  var(adopted,ac)=Make(ECardPile.Discarded);CardFace.Owner=new(){fullAbilityCard=adopted.Full,AbilityCard=ac};adopted.Full.AbilityCard=null;adopted.ToggleEffect(true,CardEffects.FXTask.BurnCard);ac.CurrentCardPile=ECardPile.Lost;adopted.ToggleEffect(true,CardEffects.FXTask.LostMode);Check(adopted.Starts==1,"Adopted widget identity must win over missing or stale full-card metadata");CardFace.Owner=null;
  var(authoritative,stale)=Make(ECardPile.Hand);authoritative.Full.playerActor=new();authoritative.Full.playerActor.CharacterClass.LostAbilityCards.Add(stale);authoritative.ToggleEffect(true,CardEffects.FXTask.BurnCard);while(authoritative.Live!.MoveNext()){}authoritative.RestoreCard();Check(authoritative.Paint>=1,"Authoritative lost membership must override a stale hand pile stamp");
  authoritative.Full.playerActor.CharacterClass.LostAbilityCards.Clear();authoritative.Full.playerActor.CharacterClass.HandAbilityCards.Add(stale);stale.CurrentCardPile=ECardPile.Lost;authoritative.RestoreCard();Check(authoritative.Paint==0,"Authoritative hand recovery must override a stale lost pile stamp");
  var(recover,rc)=Make(ECardPile.Lost);recover.ToggleEffect(true,CardEffects.FXTask.BurnCard);rc.CurrentCardPile=ECardPile.Hand;recover.RestoreCard();Check(recover.Paint==0,"Actual model recovery must restore normal artwork");
  var(retired,rtc)=Make(ECardPile.Lost);retired.ToggleEffect(true,CardEffects.FXTask.BurnCard);var obsolete=retired.Live!;BurnArtwork.RetireBurnPlayback(retired);obsolete.MoveNext();retired.RestoreCard();Check(retired.Paint==0,"A retired iterator cannot recreate an episode on pooled artwork");
  var(cancelled,cnc)=Make(ECardPile.Lost);cancelled.ToggleEffect(true,CardEffects.FXTask.BurnCard);cancelled.Live!.Dispose();cancelled.ToggleEffect(true,CardEffects.FXTask.BurnCard);Check(cancelled.Starts==2,"Disposed native playback cannot leave a permanent replay guard");
  var(activated,act)=Make(ECardPile.Round);activated.ToggleEffect(true,CardEffects.FXTask.BurnCard);act.CurrentCardPile=ECardPile.Activated;activated.RestoreCard();Check(activated.Paint>0,"Activation must not interrupt an in-progress original burn");var activatedPlayback=activated.Live!;while(activatedPlayback.MoveNext()){}Check(activated.Paint==0,"A completed activation must permit the native clean active-card look");
  var firstSeen=new ScenarioRuleLibrary.CAbilityCard{CurrentCardPile=ECardPile.Hand};var historicalOwner=new ScenarioRuleLibrary.CPlayerActor();historicalOwner.CharacterClass.LostAbilityCards.Add(firstSeen);BurnArtwork.AbilityCardUI_Init_HistoricalBurn_Patch.Prefix(firstSeen,historicalOwner);var historical=new CardEffects();historical.Full.AbilityCard=firstSeen;historical.Full.playerActor=historicalOwner;historical.ToggleEffect(true,CardEffects.FXTask.LostMode);Check(historical.Starts==0&&historical.Paint==1,"First-seen already-lost widgets must settle native artwork without a historical replay");
  var(original,model)=Make(ECardPile.Lost);original.ToggleEffect(true,CardEffects.FXTask.BurnCard);while(original.Live!.MoveNext()){}BurnArtwork.RetireBurnPlayback(original);var recreated=new CardEffects();recreated.Full.AbilityCard=model;recreated.ToggleEffect(true,CardEffects.FXTask.LostMode);Check(recreated.Starts==0&&recreated.Paint==1,"Completed original burns must survive widget recreation without replay");
  recreated.RestoreCard();Check(recreated.Paint==1,"Historical native settle must survive a standalone reset without blue flash");recreated.ToggleEffect(true,CardEffects.FXTask.LostMode);Check(recreated.Starts==0&&recreated.Paint==1,"Historical native settle must survive later resets and alias requests");
  model.CurrentCardPile=ECardPile.Hand;recreated.RestoreCard();model.CurrentCardPile=ECardPile.Lost;recreated.ToggleEffect(true,CardEffects.FXTask.BurnCard);Check(recreated.Starts==1,"Model history must retire on genuine recovery before another loss");
  var(existing,ec)=Make(ECardPile.Lost);existing.Full.playerActor=new();existing.Full.playerActor.CharacterClass.LostAbilityCards.Add(ec);existing.ToggleEffect(true,CardEffects.FXTask.BurnCard);BurnArtwork.AbilityCardUI_Init_HistoricalBurn_Patch.Prefix(ec,existing.Full.playerActor);Check(!BurnArtwork.ModelBurns.GetValue(ec,_=>throw new Exception()).Completed,"Initializing another widget must not finish an original running burn");
  var(construction,con)=Make(ECardPile.Hand);construction.ThrowOwner=true;IEnumerator raw=new NativeProbe();var preserved=raw;BurnArtwork.BurnCardTimeline_PreserveSpentStart_Patch.Postfix(construction,true,ref preserved);Check(ReferenceEquals(raw,preserved),"Mod-only interception failure must preserve the original native iterator");
  var(nativeError,ne)=Make(ECardPile.Hand);var probe=new NativeProbe{Throw=true};IEnumerator forwarded=probe;BurnArtwork.BurnCardTimeline_PreserveSpentStart_Patch.Postfix(nativeError,true,ref forwarded);try{forwarded.MoveNext();throw new Exception("Native failure was swallowed");}catch(InvalidOperationException ex){Check(ReferenceEquals(ex,probe.Error),"Native execution exception identity must remain unchanged");}
  var(primary,pc)=Make(ECardPile.Lost);primary.ToggleEffect(true,CardEffects.FXTask.BurnCard);var primaryIterator=primary.Live!;var follower=new CardEffects();follower.Full.AbilityCard=pc;follower.ToggleEffect(true,CardEffects.FXTask.LostMode);var followerIterator=follower.Live!;for(int i=0;i<10;i++){follower.ToggleEffect(true,CardEffects.FXTask.BurnCard);Check(followerIterator.MoveNext()&&follower.Starts==0&&primary.Starts==1,"A replacement widget must wait on the original burn without starting another ramp");}while(primaryIterator.MoveNext()){}Check(!followerIterator.MoveNext()&&follower.Paint==1&&follower.Starts==0,"A replacement widget must receive settled native output after original completion");Check(BurnArtwork.ModelBurns.GetValue(pc,_=>throw new Exception()).Running==null,"Completed model history must release its original widget reference");
  var(retiring,rt)=Make(ECardPile.Lost);retiring.ToggleEffect(true,CardEffects.FXTask.BurnCard);var waiting=new CardEffects();waiting.Full.AbilityCard=rt;waiting.ToggleEffect(true,CardEffects.FXTask.LostMode);var waiter=waiting.Live!;BurnArtwork.RetireBurnPlayback(retiring);Check(!waiter.MoveNext()&&waiting.Paint==1,"Retiring the primary must release replacement waiters without another ramp");
  var(recoverPrimary,rp)=Make(ECardPile.Lost);recoverPrimary.ToggleEffect(true,CardEffects.FXTask.BurnCard);var recoveringFollower=new CardEffects();recoveringFollower.Full.AbilityCard=rp;recoveringFollower.ToggleEffect(true,CardEffects.FXTask.LostMode);var recoveringWaiter=recoveringFollower.Live!;rp.CurrentCardPile=ECardPile.Hand;recoverPrimary.RestoreCard();Check(!recoveringWaiter.MoveNext()&&recoveringFollower.Paint==0,"Original recovery must release waiters without painting a new lost state");
  var(steady,sc)=Make(ECardPile.Lost);steady.ToggleEffect(true,CardEffects.FXTask.BurnCard);var obsoleteFollower=new CardEffects();obsoleteFollower.Full.AbilityCard=sc;obsoleteFollower.ToggleEffect(true,CardEffects.FXTask.LostMode);var oldFollower=obsoleteFollower.Live!;BurnArtwork.RetireBurnPlayback(obsoleteFollower);Check(!oldFollower.MoveNext()&&obsoleteFollower.Paint==0,"Retired follower iterators must stop without painting recycled artwork");Check(steady.Live!.MoveNext(),"Retiring a follower must not cancel the primary burn");
  var retargeted=new CardEffects();retargeted.Full.AbilityCard=sc;retargeted.ToggleEffect(true,CardEffects.FXTask.LostMode);var staleFollower=retargeted.Live!;retargeted.Full.AbilityCard=new(){CurrentCardPile=ECardPile.Hand};Check(!staleFollower.MoveNext()&&retargeted.Paint==0,"Retargeted follower iterators must stop without altering the new card");
  var(normal,nc)=Make(ECardPile.Hand);normal.ToggleEffect(true,CardEffects.FXTask.DiscardMode);Check(normal.Discards==1,"Unrelated normal discard presentation must remain native");
  var(preview,previewCard)=Make(ECardPile.Discarded); preview.Full.playerActor=new(); preview.Full.playerActor.CharacterClass.DiscardedAbilityCards.Add(previewCard);
  CardsHandManager.Instance=new(); CardsHandManager.Instance.Hand.ShortRestedCard=previewCard;preview.Paint=.7f;
  for(int hover=0;hover<30;hover++){preview.ToggleEffect(false,CardEffects.FXTask.BurnCard);Check(preview.Paint==.7f && preview.Resets==0 && preview.Live==null,"Uncommitted short-rest hover must retain spent artwork without a premature flame preview");}
  preview.ToggleEffect(true,CardEffects.FXTask.BurnCard); Check(preview.Starts==1,"Confirming the same hovered rest offer must start its native burn exactly once");
  preview.Full.playerActor.CharacterClass.DiscardedAbilityCards.Clear();preview.Full.playerActor.CharacterClass.LostAbilityCards.Add(previewCard);previewCard.CurrentCardPile=ECardPile.Lost;
  while(preview.Live!.MoveNext()){} preview.ToggleEffect(false,CardEffects.FXTask.BurnCard);Check(preview.Starts==1 && preview.Paint>=1,"Completed rest artwork must remain burnt after hover exits");
  var(otherPreview,otherCard)=Make(ECardPile.Discarded);otherPreview.Full.playerActor=preview.Full.playerActor;otherPreview.Full.playerActor.CharacterClass.DiscardedAbilityCards.Add(otherCard);otherPreview.ToggleEffect(false,CardEffects.FXTask.BurnCard);Check(otherPreview.Paint==1 && otherPreview.Resets==1,"Unrelated native burn previews must retain their original behavior");
  CardsHandManager.Instance.Hand.ShortRestedCard=otherCard;otherPreview.Paint=.7f;int redrawResets=otherPreview.Resets;
  otherPreview.ToggleEffect(false,CardEffects.FXTask.BurnCard);Check(otherPreview.Paint==.7f && otherPreview.Resets==redrawResets,"Redrawn short-rest offer must retain its own spent artwork");
  otherPreview.ToggleEffect(false,CardEffects.FXTask.DiscardMode);Check(otherPreview.Discards==1,"Leaving an unaccepted hover must allow the native discarded-pile refresh");
  CardsHandManager.Instance.Hand.ShortRestedCard=null;otherPreview.ToggleEffect(false,CardEffects.FXTask.BurnCard);Check(otherPreview.Resets==redrawResets+2,"Cancelling the rest must retire preview suppression");
  preview.Full.playerActor.CharacterClass.LostAbilityCards.Clear();preview.Full.playerActor.CharacterClass.HandAbilityCards.Add(previewCard);previewCard.CurrentCardPile=ECardPile.Hand;preview.RestoreCard();
  preview.Full.playerActor.CharacterClass.HandAbilityCards.Clear();preview.Full.playerActor.CharacterClass.DiscardedAbilityCards.Add(previewCard);previewCard.CurrentCardPile=ECardPile.Discarded;CardsHandManager.Instance.Hand.ShortRestedCard=previewCard;preview.Paint=.7f;
  preview.ToggleEffect(false,CardEffects.FXTask.BurnCard);Check(preview.Paint==.7f,"Recovered card offered in another rest must retain its spent preview");preview.ToggleEffect(true,CardEffects.FXTask.BurnCard);Check(preview.Starts==2,"A genuinely recovered card must burn again on later confirmation");
  CardsHandManager.Instance=null;
  Console.WriteLine($"Burn replay: {count} runtime assertions passed.");
 }
}
