using UnityEngine;
using ScenarioRuleLibrary;

namespace GloomhavenVR.Core;

// =================================================================================================
//  HAUNT FIGURES — THE APPARITIONS THEMSELVES. What appears, where, for how long, walking which way,
//  and why each one is frightening. Everything in this file is expressed in the ROOM'S OWN
//  coordinates, against landmarks the bake actually built.
// =================================================================================================

internal static partial class HauntFigures
{
    // =============================================================================================
    //  WHY EVERY COORDINATE BELOW IS A LANDMARK AND NOT A NUMBER SOMEBODY LIKED
    //
    //  The two rooms are generated by unity/.../Editor/BuildEnvironmentRooms.cs, and their
    //  interesting features are DERIVED rather than typed: the cellar window is a Rect that is then
    //  SNAPPED to the wall mesh's 0.16 m cell grid (SnappedHole, :2178), the stair doorway is a
    //  second such Rect on a different wall, and the forest's ground height at any point is a noise
    //  function (ForestY, :7957). An apparition placed at a number that merely LOOKS right is a
    //  figure standing 8 cm inside a door jamb, or floating 30 cm above a hillside, at 13 m, in the
    //  dark, where nobody can tell what is wrong — only that something is.
    //
    //  So every position here is quoted from the bake WITH ITS LINE, the snapped values are used
    //  where the bake snaps (the stair haunt's own comment at :7534-7539 says that 8 cm of error
    //  walks a figure through the jamb), and the forest's ground is not guessed at but MIRRORED —
    //  see the Ground block at the bottom of this file for why that mirror exists and what it costs.
    //
    //  THE ROOM FRAME. The room root is world-anchored, placed exactly once and never re-seated
    //  (SkyAlternative.cs:1443-1446 — re-seating a room the player stands in reads as a player
    //  teleport, ModBuild-131 ruling). Its transform is a yaw, a translation and a UNIFORM scale, so
    //  a figure parented to it and positioned in room-local metres is automatically at the room's
    //  own scale: a 2.6 m creature is 2.6 m against an 11.5 m tree and a 3.3 m ceiling, at every
    //  board zoom, with no scale tracking of any kind. That is the entire reason these events are
    //  authored in local space and parented rather than positioned in world space.
    // =============================================================================================

    /// <summary>
    /// One apparition, fully described. A STRUCT of plain data with no behaviour, because every
    /// field here is a design decision that has to be readable next to its neighbours — the moment
    /// an event needs code of its own it stops being comparable to the other three, and "why is this
    /// one different" becomes unanswerable.
    /// </summary>
    private readonly struct HauntEvent
    {
        /// <summary>The room's card index — the id the bake's HAUNT FORCE ID TABLE prints and the
        /// Advanced-menu test buttons use.</summary>
        internal readonly int Card;

        /// <summary>For the log. English; the player never sees it.</summary>
        internal readonly string Name;

        internal readonly float Reveal;
        internal readonly float Hold;
        internal readonly float Fade;

        /// <summary>Where the walk begins and ends, in ROOM-LOCAL metres. Equal for a figure that
        /// stands still. Y is ignored in the forest, where the ground is sampled per frame.</summary>
        internal readonly Vector3 From;
        internal readonly Vector3 To;

        /// <summary>Metres, room-authored. The clone is scaled by <c>Target / CharacterManager.Height</c>
        /// — the prefab states its own height, so this is a real height and not a guessed multiplier.
        /// 0 leaves the model at its authored size.</summary>
        internal readonly float Height;

        /// <summary>The animator's <c>RunBlend</c> float — 0 stands still, ~0.5 walks, ~1 runs
        /// (ActorBehaviour.cs:79). See ANIMATION in HauntFigures.Clone.cs for why this and a
        /// transform of our own is the ONLY way to make a game monster travel.</summary>
        internal readonly float RunBlend;

        /// <summary>Room-local direction the figure faces when it is not travelling. Zero means
        /// "face the way you are walking".</summary>
        internal readonly Vector3 Face;

        /// <summary>Enemy models to try, in order — the first one this machine can actually resolve
        /// wins. The per-slot hash rotates the starting point, so the list is a preference and not a
        /// fixed casting.</summary>
        internal readonly CClass.ENPCModel[] Cast;

        internal HauntEvent(int card, string name, float reveal, float hold, float fade,
                            Vector3 from, Vector3 to, float height, float runBlend, Vector3 face,
                            CClass.ENPCModel[] cast)
        {
            Card = card; Name = name;
            Reveal = reveal; Hold = hold; Fade = fade;
            From = from; To = to;
            Height = height; RunBlend = runBlend; Face = face;
            Cast = cast;
        }

        /// <summary>Authored length before the per-slot <see cref="Haunt.Slot.DurationMul"/>.</summary>
        internal float Seconds => Reveal + Hold + Fade;
    }

    // ---- THE CELLAR --------------------------------------------------------------------------------

    /// <summary>
    /// CARD 0 — <b>WAS AM KELLERFENSTER VORBEIGEHT</b> ("what goes past the cellar window").
    ///
    /// <para><b>THE PLACE.</b> The north wall's barred window. Snapped opening (the value the wall
    /// mesh actually cuts, BuildEnvironmentRooms.cs:2178-2200 <c>SnappedHole</c>/<c>WindowCentre</c>):
    /// room-local x from −1.909 to −0.796, y from 2.200 to 2.829, wall inner face z = +4.5, outer
    /// face z = +4.84 (<c>RevealDepth = 0.34</c>, :1918). Four iron bars stand at z = 4.653 (:2530).
    /// The opening is 1.11 m wide and 0.63 m tall, and its SILL IS 2.20 m ABOVE THE CELLAR FLOOR —
    /// which is to say well above the player's head.</para>
    ///
    /// <para><b>WHY THAT MAKES THIS THE BEST EVENT IN EITHER ROOM.</b> A cellar window is at OUTSIDE
    /// GROUND LEVEL: the sill height IS the height of the ground on the other side of the wall. So a
    /// creature walking past outside is standing at room-local y = 2.20, and the 0.63 m slot shows
    /// the player its FEET AND SHINS and nothing else. You do not see a monster. You see something
    /// walk past, from the knees down, through bars, from below, and it does not look in. There is
    /// no effect to reject here — no dissolve, no glow, no shader — because the wall does all of the
    /// revealing and all of the hiding.</para>
    ///
    /// <para><b>THE MOONBEAM DIMS FOR IT, FOR FREE.</b> <c>EnvBeam.shader:262</c> reads this card's
    /// presence and dims the shaft by <c>HauntBeamDepth = 0.55</c> while it runs. The suppression
    /// mask deliberately does NOT reach the reactor path (see the class doc), so the beam still dims
    /// — but now it dims because something IS actually crossing in front of the window rather than
    /// because a card said so.</para>
    ///
    /// <para><b>THE MOTION.</b> 5.5 m along the wall at z = +5.25 (0.41 m beyond the outer face, so
    /// behind the bars and framed by the 0.34 m reveal), from x = +1.6 to x = −3.9 or the reverse —
    /// a per-slot hash decides which way, because a thing that always walks the same way is a
    /// mechanism. At the walk speed below it is out of the opening's 1.11 m in about 1.1 s.</para>
    ///
    /// <para><b>THE CAST.</b> Living Bones first: bare shins walking past a barred window is the
    /// clearest silhouette in the game at that framing, it is base-game, and it is the model most
    /// likely to already be resident in a cellar scenario. Living Corpse and Cultist behind it.</para>
    /// </summary>
    private static readonly HauntEvent CellarWindow = new(
        0, "the thing that goes past the cellar window",
        // The envelope is almost nothing on both ends ON PURPOSE. The dissolve exists only as a
        // safety net for an oblique sightline through the reveal; the geometry is what reveals and
        // hides, and an authored fade would put back exactly the "obvious effect" look this whole
        // feature exists to get rid of.
        reveal: 0.35f, hold: 4.80f, fade: 0.35f,
        from: new Vector3(1.60f, 2.20f, 5.25f),
        to: new Vector3(-3.90f, 2.20f, 5.25f),
        height: 0f,          // its own size: this is a creature standing on real ground outside
        runBlend: 0.42f,     // a walk, not a hurry — it is not going anywhere in particular
        face: Vector3.zero,  // faces the way it walks
        cast: new[] { CClass.ENPCModel.LivingBones, CClass.ENPCModel.LivingCorpse, CClass.ENPCModel.Cultist });

    /// <summary>
    /// CARD 4 — <b>WAS OBEN AN DER TREPPENTÜR VORBEIGEHT</b> ("what crosses the stair doorway").
    ///
    /// <para><b>THE PLACE.</b> The west wall's stair doorway. Snapped opening
    /// (BuildEnvironmentRooms.cs:7540-7541, which uses the SNAPPED rect and says why): wall plane
    /// x = −5.25, z from 1.658 to 3.237, floor to y = 2.357. Behind it is a shaft 2.2 m deep and
    /// 1.6 m wide (<c>BuildShaft</c>, :2797-2801) that ends in a pitch-black cap at x = −7.40
    /// (:2805). Six steps climb away to the north-west and darken from tint 0.85 to 0.12 as they
    /// go (:2784-2795). There is no landing modelled — the shaft simply goes black.</para>
    ///
    /// <para><b>THE MOTION, AND WHY THE OCCLUSION IS FREE.</b> The figure walks along Z at
    /// x = −6.30, i.e. 1.05 m BEHIND the wall plane, inside the shaft. Everything left and right of
    /// the shaft's own side walls is solid room — so the figure is invisible for most of its walk,
    /// steps into view across the 1.58 m the doorway is open, and is gone. 4.2 m of travel in 2.6 s;
    /// visible for roughly nine tenths of a second. That is the user's "vorbeilaufen", framed by a
    /// door, at 5.8 m, in a room whose only other light is a candle.</para>
    ///
    /// <para><b>IT IS 2.6 m TALL AND YOU NEVER SEE ITS HEAD.</b> The doorway is 2.357 m; the figure
    /// is scaled to 2.6 m against the prefab's own stated <c>CharacterManager.Height</c>. The
    /// shader-drawn card this replaces used 2.55 m for exactly this reason and the reason is worth
    /// restating: a creature you can see all of is a creature you have measured. There is nothing in
    /// a black shaft to compare it against, so the scale reads as "too tall" rather than as
    /// "scaled".</para>
    ///
    /// <para><b>THE CAST.</b> Lean, upright silhouettes — at 2.6 m a bulky model reads as a scaling
    /// artefact while a thin one reads as wrong in the right way.</para>
    /// </summary>
    private static readonly HauntEvent CellarStair = new(
        4, "the thing that crosses the stair doorway",
        reveal: 0.30f, hold: 2.00f, fade: 0.30f,
        from: new Vector3(-6.30f, 0f, 0.40f),
        to: new Vector3(-6.30f, 0f, 4.60f),
        height: 2.60f,
        runBlend: 0.55f,
        face: Vector3.zero,
        cast: new[] { CClass.ENPCModel.BoneRanger, CClass.ENPCModel.LivingBones, CClass.ENPCModel.Cultist });

    // ---- THE NIGHT FOREST --------------------------------------------------------------------------

    /// <summary>
    /// CARD 2 — <b>DER ZUSCHAUER</b> ("the watcher").
    ///
    /// <para><b>THE PLACE.</b> Bearing 162°, 16.5 m out — room-local (+5.10, ground, −15.69), the
    /// anchor the shader card already used (BuildEnvironmentRooms.cs:10570, <c>OnGround(162, 16.5)</c>
    /// with the bake's own compass convention x = sin·r, z = cos·r, :10426). That radius puts it in
    /// the THIRD trunk band (15.5–21.5 m, 34 trunks, :7990) so there are trunks in front of it, and
    /// past the ground-darkness curve's knee (<c>SmoothStep(1, 0.015, InverseLerp(5.2, 11.5, r))</c>,
    /// :9297) so the ground under it is almost black.</para>
    ///
    /// <para><b>IT DOES NOTHING. THAT IS THE EVENT.</b> It stands, facing the clearing, at 2.7 m,
    /// playing its own idle — which for every monster in this game is a slow weight shift and a
    /// breath, i.e. exactly enough motion to be certain it is not a tree. It fades UP over three and
    /// a half seconds, which is slow enough that it is never caught arriving; it holds for five; and
    /// then it is INSTANTLY GONE, with no fade at all. The asymmetry is the whole trick and it is
    /// the same one EnvHaunt.cginc's envelope block argues for: a thing that fades in is never seen
    /// to arrive, and a thing that vanishes between one frame and the next leaves the player unable
    /// to decide whether it was ever there. Being startled is forbidden; being unsure is the
    /// goal.</para>
    ///
    /// <para><b>THE CAST.</b> Robed and upright. A Cultist at 16.5 m, motionless, at 2.7 m tall,
    /// half behind a trunk, is the single most economical piece of horror the game's own asset list
    /// can supply.</para>
    /// </summary>
    private static readonly HauntEvent ForestWatcher = new(
        2, "the watcher at the treeline",
        reveal: 3.50f, hold: 5.00f, fade: 0.00f,   // INSTANT vanish — see the paragraph above
        from: new Vector3(5.10f, 0f, -15.69f),
        to: new Vector3(5.10f, 0f, -15.69f),       // it does not move
        height: 2.70f,
        runBlend: 0f,
        face: Vector3.zero,                        // resolved to "toward the clearing" at spawn
        cast: new[] { CClass.ENPCModel.HighCultist, CClass.ENPCModel.Cultist, CClass.ENPCModel.LivingSpirit });

    /// <summary>
    /// CARD 3 — <b>WAS ZWISCHEN DEN STÄMMEN DURCHGEHT</b> ("what passes between the trunks").
    ///
    /// <para><b>THE PLACE.</b> Bearing 190°, 13.0 m out — room-local (−2.26, ground, −12.80), the
    /// shader card's own anchor (BuildEnvironmentRooms.cs:10589). It travels TANGENTIALLY, along
    /// <c>cross(up, ToClearing)</c> ≈ (+0.985, 0, −0.174), which is the direction that keeps its
    /// distance from the player constant — so it neither approaches nor retreats, it simply goes
    /// past. 6.8 m of travel, 3.4 m either side of the anchor.</para>
    ///
    /// <para><b>THE TRUNKS DO THE WORK.</b> 13 m is inside the second trunk band (10.0–15.5 m, 22
    /// trunks of base radius 0.18–0.32 m, :7989) with the first band (6.2–10.0 m, 16 trunks of
    /// 0.23–0.40 m) between it and the player. Over 6.8 m of lateral travel it passes behind several
    /// of them: the player gets three or four separate glimpses of the same thing rather than one
    /// continuous view of it, which is what makes a walking figure read as a walking figure that is
    /// TRYING NOT TO BE SEEN. None of that is authored. It is what happens when a real object walks
    /// behind real trees.</para>
    ///
    /// <para><b>THE GROUND IS FOLLOWED, NOT ASSUMED.</b> At 13 m the forest floor swings through
    /// roughly ±0.3 m (<c>ForestY</c>, :7957 — see the Ground block below). A figure at y = 0 would
    /// wade or float, and at this distance that reads as "the effect is broken" rather than as
    /// anything frightening. The height is therefore sampled per frame along the walk, which also
    /// buys the gait a small rise and fall for free.</para>
    ///
    /// <para><b>THE CAST.</b> Something that walks and is recognisably wrong: a Living Corpse
    /// shambling, a Hound trotting, a Living Bones striding. All base-game.</para>
    /// </summary>
    private static readonly HauntEvent ForestCross = new(
        3, "the thing that passes between the trunks",
        reveal: 1.00f, hold: 2.40f, fade: 0.80f,
        from: new Vector3(-2.26f - 3.4f * 0.985f, 0f, -12.80f - 3.4f * -0.174f),
        to: new Vector3(-2.26f + 3.4f * 0.985f, 0f, -12.80f + 3.4f * -0.174f),
        height: 2.20f,
        runBlend: 0.55f,
        face: Vector3.zero,
        cast: new[] { CClass.ENPCModel.LivingCorpse, CClass.ENPCModel.Hound, CClass.ENPCModel.LivingBones });

    // ---- the takeover set ---------------------------------------------------------------------------

    /// <summary>
    /// Which of the room's cards this lane was DESIGNED to take over. Stated once, here; the
    /// suppression mask, the log line and the event lookup are all derived from it, never typed
    /// again.
    ///
    /// <para>To suppress a card WITHOUT replacing it — should the user decide that one of the
    /// remaining shader apparitions should simply stop happening — adding its index here and giving
    /// <see cref="EventFor"/> an event with an empty cast is the whole change: the mask would then
    /// never include it (because <see cref="IsMine"/> requires a castable creature) and the card
    /// would keep being drawn. Making it stop entirely instead is a one-line change to
    /// <see cref="MaskFor"/>, and is called out here so that decision is a decision rather than an
    /// archaeology exercise.</para>
    /// </summary>
    private static bool IsMineByDesign(SkyStyle style, int card) =>
        style == SkyStyle.Cellar ? card == 0 || card == 4
                                 : card == 2 || card == 3;

    /// <summary>
    /// True when this lane, rather than <c>EnvHaunt.shader</c>, actually plays this card RIGHT NOW
    /// on THIS machine — design intent AND a creature that resolved.
    ///
    /// <para><b>THE ROSTER TEST IS PART OF THE PREDICATE, AND THAT IS THE WHOLE SAFETY PROPERTY.</b>
    /// The suppression mask is derived from this same function, so a card can never be suppressed
    /// without being replaceable, nor replaced without being suppressed. If a machine cannot resolve
    /// any of an event's cast — a trimmed install, an asset system that has not finished coming up —
    /// that card is simply not ours, the mask does not claim it, and the player sees the
    /// shader-drawn apparition exactly as before.</para>
    /// </summary>
    private static bool IsMine(SkyStyle style, int card) =>
        IsMineByDesign(style, card) && Roster.CanCast(EventFor(style, card).Cast);

    /// <summary>
    /// How long this card's event actually LASTS when a figure plays it, in shared-clock seconds —
    /// or 0 when the card is not a figure card on this machine.
    ///
    /// <para>WHY IT IS PUBLIC. <c>Haunt.ForceLoopSeconds</c> decides how often a LATCHED test trigger
    /// re-anchors, and it derives that from <c>CardSeconds</c> — the SHADER card's authored
    /// reveal+hold+fade. For a card a figure has taken over, those two numbers are unrelated: the
    /// shader's forest card 3 is 0.34 s while the figure's crossing runs 4.2 s. The result, visible
    /// in the ModBuild 146 hardware log, is a forced test that re-anchors NINE TIMES without the
    /// figure ever finishing its walk — i.e. the one tool the user has for looking at these events
    /// could not show him a whole one. The loop has to be the length of the thing that is actually
    /// drawn, so the side that knows it has to say.</para>
    /// </summary>
    internal static float FigureSeconds(SkyStyle style, int card)
    {
        if (!IsMine(style, card))
            return 0f;
        return EventFor(style, card).Seconds;
    }

    /// <summary>The bitmask published as <c>_GhvrHauntFigures.x</c> — derived from
    /// <see cref="IsMine"/> rather than typed, for the reason above.</summary>
    private static float MaskFor(SkyStyle style)
    {
        int mask = 0;
        for (int c = 0; c < Haunt.EventCount; c++)
            if (IsMine(style, c))
                mask |= 1 << c;
        return mask;
    }

    private static string CardList(SkyStyle style)
    {
        var sb = new System.Text.StringBuilder(48);
        for (int c = 0; c < Haunt.EventCount; c++)
        {
            if (!IsMine(style, c))
                continue;
            if (sb.Length > 0) sb.Append(", ");
            sb.Append(c).Append(" (").Append(EventFor(style, c).Name).Append(')');
        }
        return sb.Length > 0 ? sb.ToString() : "none";
    }

    private static HauntEvent EventFor(SkyStyle style, int card) =>
        style == SkyStyle.Cellar ? (card == 0 ? CellarWindow : CellarStair)
                                 : (card == 2 ? ForestWatcher : ForestCross);

    // =============================================================================================
    //  ARM → DRIVE → RETIRE. The life of one apparition.
    // =============================================================================================

    /// <summary>The node the figure hangs under, named <c>Haunt&lt;card&gt;</c>.</summary>
    private static GameObject? _anchor;

    /// <summary>Which way round the walk runs this time — a per-slot hash, so both clients agree.</summary>
    private static bool _reversed;

    /// <summary>Resolved once at arm time and then held, so the figure cannot change species or
    /// facing mid-event if anything about the resolve ever became time-dependent.</summary>
    private static string _model = string.Empty;

    private static Quaternion _standRot = Quaternion.identity;

    /// <summary>
    /// Open the event: create the anchor node the audio cue looks for, decide the creature and the
    /// direction from the shared clock, and ask the clone factory to start loading. Nothing is
    /// visible yet — <see cref="ArmLeadSeconds"/> seconds of head start is the whole point.
    ///
    /// <para><b>THE ANCHOR NODE IS THE AUDIO INTEGRATION, AND IT IS THE ONLY ONE.</b>
    /// <c>EnvSound.HauntPosition</c> (EnvSound.cs:1001-1022) already looks for a descendant of the
    /// room root named exactly <c>Haunt0</c>…<c>Haunt5</c> and plays that card's cue from its
    /// renderer bounds — its doc comment says in as many words that it was written as a seam for
    /// "another lane rebuilding all twelve apparitions as real 3D geometry in this same round", and
    /// this is that lane. So the cue lands on the figure, and it FOLLOWS the figure as it walks,
    /// with not one line of coupling between the two files.</para>
    ///
    /// <para><b>IT IS CREATED PER EVENT AND DESTROYED WITH IT, deliberately.</b> A permanent set of
    /// <c>Haunt0</c>/<c>Haunt4</c> nodes would be cheaper, but <c>HauntPosition</c>'s SECOND
    /// fallback is "any descendant whose name starts with Haunt", and a permanent node would
    /// therefore capture the cues of the cards this lane does NOT own — silently moving the
    /// handprints' and the bookshelf's sounds onto the window. Existing only during our own slot
    /// leaves every other card's behaviour byte-identical to today's.</para>
    /// </summary>
    private static void Arm(SkyStyle style, int card, float slotIndex)
    {
        HauntEvent ev = EventFor(style, card);

        // WHICH WAY ROUND — hash channel 10. Channels 0/1/3/4/5/6/7 are the schedule's own
        // (Haunt.Schedule.cs), 2 is EnvSound's per-event variation and 13 is the rat's stare, so
        // 9/10/11 are this feature's and nothing else reads them. Deterministic, therefore shared.
        _reversed = Haunt.Hash(slotIndex, 10f) >= 0.5f;

        // WHICH CREATURE — hash channel 9, used to ROTATE the cast list rather than to index it, so
        // the preference order still decides quality and the hash only decides variety. A machine
        // that can resolve only one of the three shows that one every time, which is correct.
        _model = Roster.Pick(ev.Cast, Haunt.Hash(slotIndex, 9f), out CClass.ENPCModel picked);
        if (_model.Length == 0)
        {
            // Nothing in this event's cast is available. ONE line, and the slot is simply quiet —
            // the mask has already suppressed the shader card for this room, so the honest outcome
            // is a quiet slot rather than a substitute creature that was never designed for the
            // framing. The next slot tries again.
            VRLog.Info("Core", $"HAUNT FIGURES: {style} card {card} ({ev.Name}) is quiet this slot — none of "
                               + $"its cast ({Roster.Describe(ev.Cast)}) resolved to a base-game enemy prefab "
                               + "on this machine. No apparition rather than a wrong one.");
            _card = -1;
            return;
        }

        _anchor = new GameObject("Haunt" + card);
        _anchor.transform.SetParent(_room, worldPositionStays: false);
        Vector3 start = PathAt(style, ev, 0f);
        _anchor.transform.localPosition = start;

        // FACING. "Toward the clearing" for a figure that stands, "the way you walk" for one that
        // travels — both resolved ONCE here, in room-local space, and then never touched again.
        // NOTHING IN THIS FEATURE MAY EVER RE-ORIENT WITH HEAD MOVEMENT (permanent project rule):
        // there is no camera read anywhere in this file, and a facing derived from the walk cannot
        // acquire one by accident.
        Vector3 dir = ev.From == ev.To
            ? (ev.Face != Vector3.zero ? ev.Face : new Vector3(-ev.From.x, 0f, -ev.From.z))
            : (_reversed ? ev.From - ev.To : ev.To - ev.From);
        dir.y = 0f;
        _standRot = dir.sqrMagnitude > 1e-6f
            ? Quaternion.LookRotation(dir.normalized, Vector3.up)
            : Quaternion.identity;
        _anchor.transform.localRotation = _standRot;

        // THE ROOM ROOT RIDES ALONG, and only for its LIGHT. The clone factory reads the room's
        // baked rig (_AmbUp/_DirDir/_L*Pos, written per material by BuildEnvironmentRooms.ApplyRig)
        // off one of its materials so the apparition can be lit by the same moon and the same
        // candles as the wall behind it — see the Lighting block in HauntFigures.Clone.cs for why
        // that is read back rather than mirrored, and why it is delivered as per-renderer SH rather
        // than as real Unity lights. The style goes with it because the two rooms answer the element
        // channel differently and _GhvrIndoor is what tells them apart on the GPU side.
        Clone.Request(_model, picked, ev, _anchor.transform, _room, style);

        VRLog.Info("Core", $"HAUNT FIGURES: {style} card {card} ({ev.Name}) armed at shared clock "
                           + $"{_startClock:F2}s for {ev.Seconds * _durMul:F2}s — model '{_model}' ({picked}), "
                           + $"walking {(_reversed ? "the other way" : "the authored way")}, room-local "
                           + $"{start:F2} to {PathAt(style, ev, 1f):F2}. Creature and direction are hashes of "
                           + $"slot {slotIndex:F0} on channels 9 and 10, so every client in this scenario "
                           + "picked the same ones.");
    }

    /// <summary>
    /// One frame of a running apparition: where it is, which way it faces, how present it is, and
    /// whether it should still exist. All of it is a function of the shared clock and nothing else.
    /// </summary>
    private static void Drive(SkyStyle style, float clock)
    {
        HauntEvent ev = EventFor(style, _card);
        float len = Mathf.Max(ev.Seconds * _durMul, 0.05f);
        float t = clock - _startClock;

        // Before the start the figure is loading and MUST NOT be visible: the anchor exists (so the
        // audio cue can find it) but presence is 0, which the clone factory reads as "stay hidden".
        float u = Mathf.Clamp01(t / len);
        float presence = Envelope(t, ev, _durMul);

        if (_anchor != null)
            _anchor.transform.localPosition = PathAt(style, ev, u);

        Clone.Drive(presence, ev.RunBlend);
    }

    /// <summary>
    /// The presence envelope — the C# twin of <c>GhvrHauntEnvelope</c> (EnvHaunt.cginc:310), kept
    /// deliberately identical in SHAPE so a figure and the shader apparitions in the same room read
    /// as one family: a smoothstep up over <c>reveal</c>, a hold, and either a smoothstep down or,
    /// when <c>fade</c> is zero, a hard step. The hard step is not an optimisation — it is the
    /// instant vanish the watcher is built around, and the cginc's own comment explains why it must
    /// be a real step rather than a collapsed smoothstep.
    ///
    /// <para>It is a TWIN and not a mirror: nothing depends on the two agreeing to the bit, because
    /// they never shade the same pixel. That is why this one is allowed to be a re-implementation
    /// while <see cref="Haunt.Resolve"/> is held to being character-for-character the shader's.</para>
    /// </summary>
    private static float Envelope(float t, in HauntEvent ev, float mul)
    {
        float r = Mathf.Max(ev.Reveal * mul, 1e-4f);
        float h = ev.Hold * mul;
        float f = ev.Fade * mul;
        if (t <= 0f)
            return 0f;
        float up = Mathf.SmoothStep(0f, 1f, Mathf.Clamp01(t / r));
        float down = f > 1e-4f
            ? Mathf.SmoothStep(0f, 1f, Mathf.Clamp01((r + h + f - t) / f))
            : (t <= r + h ? 1f : 0f);
        return Mathf.Clamp01(up * down);
    }

    /// <summary>Room-local position at walk fraction <paramref name="u"/>, with the forest's ground
    /// followed and the cellar's ignored (the cellar floor undulates by ±6 mm,
    /// BuildEnvironmentRooms.cs:1861 — below the threshold of anything).</summary>
    private static Vector3 PathAt(SkyStyle style, in HauntEvent ev, float u)
    {
        Vector3 a = _reversed ? ev.To : ev.From;
        Vector3 b = _reversed ? ev.From : ev.To;
        Vector3 p = Vector3.Lerp(a, b, Mathf.Clamp01(u));
        if (style == SkyStyle.SwampNight)
            p.y = Ground.ForestY(p.x, p.z);
        return p;
    }

    /// <summary>Drop the running apparition and its anchor. Idempotent.</summary>
    private static void Retire(string why)
    {
        Clone.Release(why);
        if (_anchor != null)
        {
            Object.Destroy(_anchor);
            _anchor = null;
        }
        _card = -1;
        _model = string.Empty;
    }

    // =============================================================================================
    //  THE GROUND — a MIRROR of the forest's height field, and the argument for why it is one.
    // =============================================================================================

    /// <summary>
    /// The forest floor's height at a room-local (x, z).
    ///
    /// <para><b>WHY THIS IS A MIRROR AND NOT A MEASUREMENT.</b> Three ways to know the ground height
    /// under a figure were available and two of them are closed. (1) A RAYCAST needs a collider, and
    /// the room ships none — deliberately, so the hand laser can never catch the environment
    /// (SkyAlternative.cs's collider strip). Adding one would put 30 m of terrain in front of every
    /// pointer in the game. (2) SAMPLING THE GROUND MESH is closed too: reading vertices at runtime
    /// needs <c>Mesh.isReadable</c>, which costs a permanent CPU copy of the mesh, and the bake
    /// turns readability OFF for the assets it imports (BuildEnvironmentRooms.cs:210). (3) So the
    /// height field is mirrored, which is what is left, and it is exact rather than approximate.</para>
    ///
    /// <para><b>WHAT THE MIRROR COSTS, STATED PLAINLY.</b> This is the same class of debt
    /// <c>Haunt.Schedule.cs</c> records for the schedule hash, and the same guard applies: the lint
    /// <c>scripts/check-mirrors.sh</c> cannot cover it (it compares <c>const</c> declarations inside
    /// <c>src/</c>, and the other side of this pair is a private static method under <c>unity/</c>),
    /// so the guard is this comment plus the cited line numbers.
    /// <b>The other side is <c>BuildEnvironmentRooms.cs</c>: <c>ForestY</c> :7957-7981,
    /// <c>PathDist</c> :7942-7952, <c>PathFade</c> :7954-7955, <c>Fbm2</c> :970-979,
    /// <c>Noise2</c> :960-968, <c>Hash3</c> :950-958.</b> Whoever changes the forest's relief must
    /// change this block, and the failure mode if they do not is specific and visible: an apparition
    /// wading through the ground or floating above it at 13 m. It cannot cause a desync, a
    /// mismatch or a crash — every client runs the same mirror.</para>
    ///
    /// <para><b>FLOAT AND THIS ORDER OF OPERATIONS</b>, for the reason the schedule mirror gives:
    /// the bake computes in single precision and reassociating would give a number that is very
    /// nearly right, which is the worst kind.</para>
    /// </summary>
    private static class Ground
    {
        private static bool _logged;

        internal static void Forget() => _logged = false;

        /// <summary>MIRROR of <c>BuildEnvironmentRooms.PathPts</c> :7932-7938 — the crooked path
        /// that leaves the clearing to the south-west, trodden into a shallow hollow.</summary>
        private static readonly Vector2[] PathPts =
        {
            new(0.6f, -1.2f), new(-0.9f, -3.4f), new(-2.6f, -5.2f),
            new(-3.4f, -7.6f), new(-2.7f, -10.3f), new(-3.9f, -12.8f),
            new(-6.4f, -14.6f), new(-9.2f, -15.6f),
        };

        /// <summary>MIRROR of <c>ForestY</c> :7957-7981.</summary>
        internal static float ForestY(float x, float z)
        {
            float r = Mathf.Sqrt(x * x + z * z);
            float lift = Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(1.7f, 4.6f, r)); // dead-flat play space
            float h = lift * (0.44f * Fbm2(x * 0.13f + 19f, z * 0.13f, 3, 981)
                              + 0.15f * Fbm2(x * 0.52f, z * 0.52f, 3, 982) - 0.27f);
            float pd = PathDist(x, z) / 0.95f;
            h -= lift * 0.075f * Mathf.Exp(-pd * pd) * PathFade(x, z);
            h += Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(19f, 28f, r))
                 * (0.9f + 3.4f * Fbm2(x * 0.145f + 7f, z * 0.145f, 3, 983)
                    * (0.45f + 0.9f * Fbm2(x * 0.055f, z * 0.055f + 21f, 2, 987)));
            if (!_logged)
            {
                _logged = true;
                VRLog.Info("Core", $"HAUNT FIGURES ground mirror live — ForestY({x:F2}, {z:F2}) = {h:F3} m. "
                                   + "This is a documented MIRROR of BuildEnvironmentRooms.cs:7957; the room "
                                   + "ships no colliders and its meshes are not CPU-readable, so a figure's "
                                   + "footing is computed rather than measured. A figure visibly wading or "
                                   + "floating in the forest means this mirror has drifted from the bake.");
            }
            return h;
        }

        /// <summary>MIRROR of <c>PathDist</c> :7942-7952.</summary>
        private static float PathDist(float x, float z)
        {
            var p = new Vector2(x, z);
            float best = float.MaxValue;
            for (int i = 0; i < PathPts.Length - 1; i++)
            {
                Vector2 a = PathPts[i], b = PathPts[i + 1], ab = b - a;
                float t = Mathf.Clamp01(Vector2.Dot(p - a, ab) / Mathf.Max(ab.sqrMagnitude, 1e-4f));
                best = Mathf.Min(best, (a + ab * t - p).magnitude);
            }
            return best;
        }

        /// <summary>MIRROR of <c>PathFade</c> :7954-7955.</summary>
        private static float PathFade(float x, float z) =>
            Mathf.SmoothStep(1f, 0f, Mathf.InverseLerp(9f, 15f, new Vector2(x, z).magnitude));

        /// <summary>MIRROR of <c>Fbm2</c> :970-979.</summary>
        private static float Fbm2(float x, float y, int oct, int seed)
        {
            float acc = 0f, amp = 1f, sum = 0f;
            for (int o = 0; o < oct; o++)
            {
                acc += amp * Noise2(x, y, seed + o * 131);
                sum += amp; amp *= 0.55f; x *= 2.03f; y *= 2.03f;
            }
            return acc / sum;
        }

        /// <summary>MIRROR of <c>Noise2</c> :960-968.</summary>
        private static float Noise2(float x, float y, int seed)
        {
            int x0 = Mathf.FloorToInt(x), y0 = Mathf.FloorToInt(y);
            float tx = x - x0, ty = y - y0;
            tx = tx * tx * (3f - 2f * tx); ty = ty * ty * (3f - 2f * ty);
            float a = Mathf.Lerp(Hash3(x0, y0, 0, seed), Hash3(x0 + 1, y0, 0, seed), tx);
            float b = Mathf.Lerp(Hash3(x0, y0 + 1, 0, seed), Hash3(x0 + 1, y0 + 1, 0, seed), tx);
            return Mathf.Lerp(a, b, ty);
        }

        /// <summary>MIRROR of <c>Hash3</c> :950-958.</summary>
        private static float Hash3(int x, int y, int z, int seed)
        {
            unchecked
            {
                uint n = (uint)(x * 73856093) ^ (uint)(y * 19349663) ^ (uint)(z * 83492791) ^ (uint)(seed * 974711);
                n *= 1274126177u; n ^= n >> 16; n *= 2246822519u; n ^= n >> 13;
                return (n & 0xFFFFFF) / 16777216f;
            }
        }
    }
}
