using UnityEngine;
using ScenarioRuleLibrary;

namespace GloomhavenVR.Core;

// =================================================================================================
//  HAUNT FIGURES — THE APPARITIONS THEMSELVES. What appears, where, for how long, walking which way,
//  and why each one is frightening. Everything in this file is expressed in the ROOM'S OWN
//  coordinates, against landmarks the bake actually built.
// =================================================================================================

internal static partial class HauntFigures
{
    // =============================================================================================
    //  WHY EVERY COORDINATE BELOW IS A LANDMARK AND NOT A NUMBER SOMEBODY LIKED
    //
    //  The two rooms are generated by unity/.../Editor/BuildEnvironmentRooms.cs, and their
    //  interesting features are DERIVED rather than typed: the cellar window is a Rect that is then
    //  SNAPPED to the wall mesh's 0.16 m cell grid (SnappedHole, :2178), the stair doorway is a
    //  second such Rect on a different wall, and the forest's ground height at any point is a noise
    //  function (ForestY, :7957). An apparition placed at a number that merely LOOKS right is a
    //  figure standing 8 cm inside a door jamb, or floating 30 cm above a hillside, at 13 m, in the
    //  dark, where nobody can tell what is wrong — only that something is.
    //
    //  So every position here is quoted from the bake WITH ITS LINE, the snapped values are used
    //  where the bake snaps (the stair haunt's own comment at :7534-7539 says that 8 cm of error
    //  walks a figure through the jamb), and the forest's ground is not guessed at but MIRRORED —
    //  see the Ground block at the bottom of this file for why that mirror exists and what it costs.
    //
    //  THE ROOM FRAME. The room root is world-anchored, placed exactly once and never re-seated
    //  (SkyAlternative.cs:1443-1446 — re-seating a room the player stands in reads as a player
    //  teleport, ModBuild-131 ruling). Its transform is a yaw, a translation and a UNIFORM scale, so
    //  a figure parented to it and positioned in room-local metres is automatically at the room's
    //  own scale: a 2.6 m creature is 2.6 m against an 11.5 m tree and a 3.3 m ceiling, at every
    //  board zoom, with no scale tracking of any kind. That is the entire reason these events are
    //  authored in local space and parented rather than positioned in world space.
    // =============================================================================================

    /// <summary>
    /// One apparition, fully described. A STRUCT of plain data with no behaviour, because every
    /// field here is a design decision that has to be readable next to its neighbours — the moment
    /// an event needs code of its own it stops being comparable to the other three, and "why is this
    /// one different" becomes unanswerable.
    /// </summary>
    private readonly struct HauntEvent
    {
        /// <summary>The room's card index — the id the bake's HAUNT FORCE ID TABLE prints and the
        /// Advanced-menu test buttons use.</summary>
        internal readonly int Card;

        /// <summary>For the log. English; the player never sees it.</summary>
        internal readonly string Name;

        internal readonly float Reveal;
        internal readonly float Hold;
        internal readonly float Fade;

        /// <summary>Where the walk begins and ends, in ROOM-LOCAL metres. Equal for a figure that
        /// stands still. Y is ignored in the forest, where the ground is sampled per frame.</summary>
        internal readonly Vector3 From;
        internal readonly Vector3 To;

        /// <summary>Metres, room-authored. The clone is scaled by <c>Target / CharacterManager.Height</c>
        /// — the prefab states its own height, so this is a real height and not a guessed multiplier.
        /// 0 leaves the model at its authored size.</summary>
        internal readonly float Height;

        /// <summary>The animator's <c>RunBlend</c> float — a BLEND WEIGHT and not a speed
        /// (ActorBehaviour.cs:79, :546-547): 0 stands still, 1 is what the game itself drives during
        /// any sustained travel. See ANIMATION in HauntFigures.Clone.cs for why this and a transform
        /// of our own is the ONLY way to make a game monster travel.
        ///
        /// <para><b>SINCE ModBuild 150 THIS IS ONLY READ FOR A FIGURE THAT STANDS</b> — i.e. where
        /// it is 0 anyway. A figure that TRAVELS has its blend derived per apparition from the path's
        /// real speed, the creature's real scale and its own locomotion clip; the authored constant
        /// (0.55 for the forest crossing, at every speed and for every creature) was the whole of the
        /// user's teleport report. <c>Clone.Gait</c> carries the argument and the arithmetic. The
        /// field is kept because a future STANDING event may legitimately want a non-zero
        /// idle-shuffle, and because the log prints it beside the derived value so the two can be
        /// compared.</para></summary>
        internal readonly float RunBlend;

        /// <summary>Room-local direction the figure faces when it is not travelling. Zero means
        /// "face the way you are walking".</summary>
        internal readonly Vector3 Face;

        /// <summary>Enemy models to try, in order — the first one this machine can actually resolve
        /// wins. The per-slot hash rotates the starting point, so the list is a preference and not a
        /// fixed casting.</summary>
        internal readonly CClass.ENPCModel[] Cast;

        internal HauntEvent(int card, string name, float reveal, float hold, float fade,
                            Vector3 from, Vector3 to, float height, float runBlend, Vector3 face,
                            CClass.ENPCModel[] cast)
        {
            Card = card; Name = name;
            Reveal = reveal; Hold = hold; Fade = fade;
            From = from; To = to;
            Height = height; RunBlend = runBlend; Face = face;
            Cast = cast;
        }

        /// <summary>Authored length before the per-slot <see cref="Haunt.Slot.DurationMul"/>.</summary>
        internal float Seconds => Reveal + Hold + Fade;
    }

    // ---- THE CELLAR --------------------------------------------------------------------------------

    /// <summary>
    /// CARD 0 — <b>WAS AM KELLERFENSTER HEREINSIEHT</b> ("what looks in at the cellar window").
    ///
    /// <para><b>THIS EVENT REPLACES ONE THE USER REJECTED, AND HIS WORDS ARE THE SPECIFICATION:</b>
    /// "Ich mag die Idee nicht dass jemand am Kellerfenster vorbeirennt. Man sieht eh nur die Füße.
    /// Ich will lieber das eine Figur hineinschaut durch das Gitter (aber mit den selben
    /// Lichtverhältnissen, dass man vlt nicht alles erkennt!)". The paragraph this deletes called the
    /// walk-past "the best event in either room" because "you see something walk past, from the knees
    /// down, through bars, from below" — the user has now watched it and calls that same property the
    /// reason it does not work. HE IS RIGHT ON THE EVIDENCE, and there were two things wrong with it
    /// that a screenshot settles:
    /// <list type="number">
    /// <item><b>From inside, feet are not a creature.</b> A pair of shins crossing a slot for a
    /// second is a detail, not an apparition — nothing about it says what it belongs to.</item>
    /// <item><b>From the tabletop vantage it was not cropped at all.</b> The player looks at the
    /// board as a DIORAMA and his head is routinely ABOVE the cellar's 3.3 m walls, which is exactly
    /// what <c>.planning/debug/nachladen1.jpg</c> is: a whole figure, from the top of its head to its
    /// feet, standing in the open beyond the north wall with nothing framing it. The event's entire
    /// design was "the wall does all of the revealing and all of the hiding", and from that vantage
    /// the wall does neither.</item>
    /// </list></para>
    ///
    /// <para><b>THE PLACE, re-read from the bake rather than from the paragraph above it</b>
    /// (BuildEnvironmentRooms.cs:3197-3212, which prints these numbers at bake time, plus
    /// <c>WindowHole</c> :2211, <c>RevealDepth</c> :2224, <c>RevealJambSplay</c>/<c>RevealCillFall</c>
    /// :2247-2248, the bars :3248-3260). The north wall's inner face is z = +4.50 and it is 0.55 m
    /// thick, so the outer face is z = +5.05. The snapped opening is x −2.068…−0.636, y 2.200…2.986;
    /// the reveal is SPLAYED, so the outer opening is x −1.966…−0.738 and its cill rises to y = 2.343.
    /// FIVE iron bars stand at z = 4.7475 (<c>barZ = hd + RevealDepth * 0.45</c>). Outside there is a
    /// real star dome and a pitch-black ground plane at the OUTER cill height
    /// (<c>AddNightOutsideWindow</c> :2609-2760).</para>
    ///
    /// <para><b>HOW A FIGURE GETS ITS FACE INTO A 0.79 m SLOT WHOSE SILL IS THE GROUND OUTSIDE.</b>
    /// This is the one real problem the event has, and it is worth stating because the obvious
    /// answers are all wrong. A creature STANDING on the outside ground has its head 1.8 m above the
    /// opening — that is the rejected walk-past, seen from the knees down. Scaling it down to 0.4 m
    /// so that its head lands in the slot makes a doll. Pitching it forward to lie prone would read
    /// correctly through the slot and read as a body floating horizontally on the ground from above.
    /// So the figure is SUNK: it stands at room-local y = 0.838 with its head at 2.788, i.e. crouched
    /// in the window well the way a person looking into a cellar window really is, and the black
    /// ground plane outside — which starts exactly at the outer face and runs 34 m — hides
    /// everything below y = 2.343 from any vantage above it. What is left is a head and the top of a
    /// pair of shoulders, in the opening, behind the bars.</para>
    ///
    /// <para><b>IT WAS 0.182 m TOO HIGH AND THE PHOTOGRAPH SETTLED IT.</b> USER, ModBuild 148,
    /// verbatim: "Die Figur die im Kellerfenster reinschaut, muss etwas tiefer gesetzt werden das ihr
    /// gesicht mittig positioniert ist (siehe Kellerfenster_figur.jpg)." That frame
    /// (<c>.planning/debug/Kellerfenster_figur.jpg</c>) shows the face cut off ABOVE the lintel —
    /// chest, one shoulder and one hand inside the opening and nothing else. THE DROP IS COMPUTED,
    /// not chosen, and every number in it is a measurement:
    /// <list type="bullet">
    /// <item>the SNAPPED opening is y 2.200…2.986 (BuildEnvironmentRooms.cs:3197-3212), so its centre
    /// is (2.200 + 2.986) / 2 = <b>2.593</b>;</item>
    /// <item>the FACE of a humanoid sits at about 0.9 of its stature above its feet, so at the old
    /// seat it was 1.02 + 0.9 × 1.95 = <b>2.775</b>;</item>
    /// <item>drop = 2.775 − 2.593 = <b>0.182 m</b>, hence y = 1.02 − 0.182 = <b>0.838</b>.</item>
    /// </list>
    /// The top of the head lands at 0.838 + 1.95 = 2.788, i.e. 0.198 m UNDER the lintel — so the whole
    /// head is inside the opening instead of half of it being over the stone, which is what the frame
    /// shows. The 0.9-of-stature figure is the one approximation here and it is the right kind: it is
    /// a property of the human silhouette rather than of any one prefab, and the cast is three hooded
    /// humanoids scaled to the same 1.95 m by <c>CharacterManager.Height</c>.</para>
    ///
    /// <para><b>AND IT IS CHECKED FROM BOTH VANTAGES, because that is what the last one failed.</b>
    /// FROM INSIDE, at eye height 1.6 m in the middle of the room: the sightline has to clear the
    /// outer cill (2.343 at z = 5.05) and stay under the flat head (2.986 at z = 5.05), which at the
    /// figure's z = 5.35 is a visible band of y 2.39…3.07. The drop moves the body DOWN through that
    /// band rather than moving the band: what used to sit in it was the chest, and what sits in it
    /// now is the face at 2.593 with the crown of the head at 2.788 — both inside, and the shoulders
    /// still cut off by the outer cill at 2.343, so nothing below the collarbone is ever shown. FROM
    /// THE TABLETOP VANTAGE, looking down past the wall top: the outside ground is an opaque black
    /// plane and the only thing standing above it is that same head and those shoulders, which reads
    /// as a creature crouched at the window — not as a bug, and not as a whole figure standing in a
    /// field. The event survives the viewpoint that killed the walk-past.</para>
    ///
    /// <para><b>THE MOONBEAM DIMS FOR IT, AND NOW IT MEANS SOMETHING.</b> <c>EnvBeam.shader:262</c>
    /// reads this card's presence and dims the shaft by <c>HauntBeamDepth = 0.55</c> while it runs;
    /// the suppression mask deliberately does not reach the reactor path (class doc). With a creature
    /// walking PAST the window the dim was a coincidence with the right timing. With a creature
    /// standing IN the window it is the actual physics of the scene: something is in front of the
    /// hole the moonlight comes through, so the shaft goes dim while it is there.</para>
    ///
    /// <para><b>THE LENGTH IS THE BAKE'S, NOT THIS FILE'S CHOICE.</b> 2.10 + 2.80 + 0.60 = 5.50 s,
    /// which is exactly <c>Haunt.CardSeconds(Cellar, 0)</c> and exactly what the bake's catalogue
    /// gives card 0. That equality is load-bearing rather than tidy: the beam's dim runs on the
    /// SHADER's envelope and the figure runs on this one, and a 5.5 s dim over an 8 s apparition
    /// would leave the shaft bright with the thing still at the window. The reveal is long (2.1 s)
    /// because the figure now fades UP OUT OF BLACK instead of dissolving (HauntFigures.Clone.cs) —
    /// slow enough that it is never seen to arrive.</para>
    ///
    /// <para><b>THE CAST.</b> Hooded and human-shaped, because the whole event is a head. The Cultist
    /// leads: it is base-game, its cowl reads as a silhouette at 4.7 m through bars, and it is one of
    /// the five models the shipped roster census actually resolved on hardware.</para>
    /// </summary>
    private static readonly HauntEvent CellarWindow = new(
        0, "the thing that looks in at the cellar window",
        reveal: 2.10f, hold: 2.80f, fade: 0.60f,     // = 5.50 s, the bake's own card length; see above
        // y = 0.838 and NOT 1.02: face 0.9 x 1.95 = 1.755 over the feet, opening centre
        // (2.200 + 2.986) / 2 = 2.593, so the seat is 2.593 - 1.755 = 0.838. See the block above.
        from: new Vector3(-1.35f, 0.838f, 5.35f),    // window centre x is -1.3523 (BuildEnvironmentRooms:2199)
        to: new Vector3(-1.35f, 0.838f, 5.35f),      // IT DOES NOT MOVE: it is looking in
        height: 1.95f,                               // head at 2.788, 0.198 m under the opening's head 2.986
        runBlend: 0f,                                // standing, playing its own idle
        face: new Vector3(0f, 0f, -1f),              // into the room, and never re-oriented afterwards
        cast: new[] { CClass.ENPCModel.Cultist, CClass.ENPCModel.LivingCorpse, CClass.ENPCModel.LivingBones });

    /// <summary>
    /// CARD 4 — <b>WER IM TREPPENSCHACHT STEHT</b> ("who stands in the stair shaft").
    ///
    /// <para><b>THIS EVENT ALSO REPLACES ONE THE USER REJECTED, AND THIS ONE WAS A REAL BUG:</b>
    /// "Bei 'Treppe' rennen (samt der Teleportation von zuvor) einfach die figuren durch die Wand an
    /// der Treppe. Das gefällt mir überhaupt nicht. Die figuren sollten nicht durch wände glitchen.
    /// Mach doch auch einfach jemand der dort steht und beobachtet im Schatten, wichtig ist nur für
    /// den Gruselfaktor dass die Lichtverhältnisse stimmen und man ihn kaum erkennt."</para>
    ///
    /// <para><b>HE IS DESCRIBING SOMETHING THE OLD PATH REALLY DID, AND THE OLD DOC ARGUED THE
    /// OPPOSITE.</b> It said: "Everything left and right of the shaft's own side walls is solid room
    /// — so the figure is invisible for most of its walk." That is false, and the numbers say so. The
    /// walk ran along Z at x = −6.30 from z = 0.40 to z = 4.60 — but the alcove it ran inside is
    /// 1.6 m wide and spans z 1.70…3.30 (<c>BuildShaft</c> is placed at
    /// <c>(-hw, 0, -hd + StairHole.xMin)</c> = (−5.25, 0, 1.70) and is
    /// <c>StairHole.width</c> = 1.6 m across, BuildEnvironmentRooms.cs:3557-3559). So the figure
    /// STARTED 1.3 m inside solid rock, walked THROUGH the shaft's z = 1.70 side wall, across the
    /// doorway, and out THROUGH its z = 3.30 side wall. Two wall crossings per run, in plain view of
    /// a player whose head is above the room. "Invisible for most of its walk" was true only of a
    /// viewer standing on the cellar floor, which is not where this player is.</para>
    ///
    /// <para><b>SO NOBODY WALKS HERE ANY MORE — someone STANDS.</b> No motion means no path, no path
    /// means no wall to cross, and the failure mode is removed rather than tuned. The figure stands
    /// on the third step (step 2 of six, its box centred at x = −6.02 and its top face at y = 0.57 —
    /// the steps are <c>BoxMesh(1.5, 0.19, 0.34)</c> placed at <c>y = 0.19 * i</c> and BoxMesh's
    /// origin is its BASE, :3544-3549, :1211-1232), in the middle of the doorway's z span, facing
    /// out into the room. It is 1.80 m tall, and THAT number is set by the DOORWAY rather than by the
    /// alcove: the lintel is at y = 2.357, so from an eye 1.6 m up in the middle of the room the
    /// sightline that grazes it is at y = 2.468 by the time it reaches the figure's x — a head at
    /// 0.57 + 1.80 = 2.37 clears that with 10 cm to spare, and one at 2.5 would be beheaded by the
    /// lintel for half the room. (The alcove's own ceiling at y = 2.60,
    /// <c>BuildShaft(2.2f, 2.6f, …)</c>, is the looser of the two limits.) The old 2.6 m giant is
    /// gone with the walk — it existed to be cropped by a doorway it was taller than, and a figure
    /// that stands still is measured by the player at leisure.</para>
    ///
    /// <para><b>WHY THIS IS THE DARKEST FRAMING IN EITHER ROOM, which is the user's own priority
    /// ("wichtig ist nur … dass die Lichtverhältnisse stimmen und man ihn kaum erkennt").</b> The
    /// alcove's own masonry is tinted to 0.28 of the room's albedo and the six steps darken from
    /// 0.85 to 0.12 as they climb (:3552-3554); the shaft ends in a pitch-black cap (:3563-3567);
    /// there is no candle, no moonbeam and no reactor anywhere near it — this file's own light block
    /// calls the stair alcove one of the room's two deliberately black corners. So the measured room
    /// level at the figure's chest is about as low as the cellar rig goes, and the darkening in
    /// HauntFigures.Clone.cs puts the creature at roughly a fiftieth of its albedo. You see that
    /// something is standing there. You do not see what.</para>
    ///
    /// <para><b>BOTH VANTAGES, and the second one is not what it looks like on paper.</b> FROM
    /// INSIDE the room it is a shape in the doorway at 5.8 m, 0.77 m behind the wall plane, framed by
    /// 1.58 m of opening and cropped at the throat by the lintel. FROM THE TABLETOP VANTAGE — head
    /// above the room's 3.3 m walls, looking down — the obvious expectation is that the alcove's own
    /// ceiling hides everything, and it does NOT: <c>BuildShaft</c>'s ceiling quad is wound with its
    /// normal at −Y (its triangles are <c>(a, c, b)</c> over
    /// <c>a = (0, h, 0), b = (−depth, h, 0), c = (−depth, h, width)</c>, :6867-6868), i.e. it faces
    /// DOWN into the shaft and <c>Cull Back</c> removes it when seen from above. So the alcove reads
    /// as an open-topped box from up there and the figure is visible in it, from above and behind,
    /// in near-total darkness — which is a second framing rather than a failure. Both were checked
    /// because the event this replaces was designed for one viewpoint and fell apart in the
    /// other.</para>
    ///
    /// <para><b>THE LENGTH IS THIS FILE'S, and it may be, unlike card 0's.</b> The bake's card 4
    /// draws nothing at all and nothing reacts to it (its own catalogue says so:
    /// "4 Stair draws nothing here"), so no shader envelope has to be matched. 2.40 + 4.60 + 0.00 =
    /// 7.0 s: a slow rise out of black, a long enough hold that a player who looks away and back
    /// finds it still there, and then it is INSTANTLY gone — the same asymmetry the forest watcher is
    /// built on, and for the same reason. The one consequence worth naming is that
    /// <see cref="EnvSound"/>'s cue window for this card is the bake's 2.60 s, so the sound belongs
    /// to the arrival and does not run the length of the apparition.</para>
    ///
    /// <para><b>THE CAST.</b> Upright and human-shaped; a watcher has to have a front. The Cultist
    /// leads for the reason it leads at the window — hooded, base-game, and one of the five the
    /// hardware roster census actually resolved.</para>
    /// </summary>
    private static readonly HauntEvent CellarStair = new(
        4, "the one who stands in the stair shaft",
        reveal: 2.40f, hold: 4.60f, fade: 0.00f,     // INSTANT vanish — see the paragraph above
        from: new Vector3(-6.02f, 0.57f, 2.45f),     // step 2's top face, mid-doorway
        to: new Vector3(-6.02f, 0.57f, 2.45f),       // IT DOES NOT MOVE: that is the whole point
        height: 1.80f,                               // head at 2.37: clears the doorway lintel's crop
        runBlend: 0f,
        face: new Vector3(1f, 0f, 0f),               // out through the doorway, into the room
        cast: new[] { CClass.ENPCModel.Cultist, CClass.ENPCModel.LivingBones, CClass.ENPCModel.LivingCorpse });

    // ---- THE NIGHT FOREST --------------------------------------------------------------------------

    /// <summary>
    /// CARD 1 — <b>DER ZUSCHAUER</b> ("the watcher"). It was card 2 until ModBuild 147 renumbered the
    /// wood's catalogue down to three cards; the <c>Card</c> field below said 2 for one build after
    /// that, which nothing read and everything quoted.
    ///
    /// <para><b>THE PLACE.</b> Bearing 162°, 16.5 m out — room-local (+5.10, ground, −15.69), the
    /// anchor the shader card already used (BuildEnvironmentRooms.cs:10570, <c>OnGround(162, 16.5)</c>
    /// with the bake's own compass convention x = sin·r, z = cos·r, :10426). That radius puts it in
    /// the THIRD trunk band (15.5–21.5 m, 34 trunks, :7990) so there are trunks in front of it, and
    /// past the ground-darkness curve's knee (<c>SmoothStep(1, 0.015, InverseLerp(5.2, 11.5, r))</c>,
    /// :9297) so the ground under it is almost black.</para>
    ///
    /// <para><b>IT DOES NOTHING. THAT IS THE EVENT.</b> It stands, facing the clearing, at 2.7 m,
    /// playing its own idle — which for every monster in this game is a slow weight shift and a
    /// breath, i.e. exactly enough motion to be certain it is not a tree. It fades UP over three and
    /// a half seconds, which is slow enough that it is never caught arriving; it holds for five; and
    /// then it is INSTANTLY GONE, with no fade at all. The asymmetry is the whole trick and it is
    /// the same one EnvHaunt.cginc's envelope block argues for: a thing that fades in is never seen
    /// to arrive, and a thing that vanishes between one frame and the next leaves the player unable
    /// to decide whether it was ever there. Being startled is forbidden; being unsure is the
    /// goal.</para>
    ///
    /// <para><b>THE CAST.</b> Robed and upright. A Cultist at 16.5 m, motionless, at 2.7 m tall,
    /// half behind a trunk, is the single most economical piece of horror the game's own asset list
    /// can supply.</para>
    /// </summary>
    private static readonly HauntEvent ForestWatcher = new(
        1, "the watcher at the treeline",
        reveal: 3.50f, hold: 5.00f, fade: 0.00f,   // INSTANT vanish — see the paragraph above
        from: new Vector3(5.10f, 0f, -15.69f),
        to: new Vector3(5.10f, 0f, -15.69f),       // it does not move
        height: 2.70f,
        runBlend: 0f,
        face: Vector3.zero,                        // resolved to "toward the clearing" at spawn
        cast: new[] { CClass.ENPCModel.HighCultist, CClass.ENPCModel.Cultist, CClass.ENPCModel.LivingSpirit });

    /// <summary>
    /// CARD 2 — <b>WAS ZWISCHEN DEN STÄMMEN DURCHGEHT</b> ("what passes between the trunks"). It was
    /// card 3 before the wood's catalogue was renumbered; see the watcher above.
    ///
    /// <para><b>IT IS THE ONLY EVENT LEFT THAT MOVES, and that is deliberate rather than incidental.</b>
    /// Both cellar events became standing figures this round on the user's own rulings, so this is
    /// the one path in the feature — which is why the wall-crossing gate below is a guard against
    /// regression rather than a check on today's content, and why the looping test trigger's restart
    /// only has one event it could ever be seen on (HauntFigures.TickBody).</para>
    ///
    /// <para><b>THE PLACE.</b> Bearing 190°, 13.0 m out — room-local (−2.26, ground, −12.80), the
    /// shader card's own anchor (BuildEnvironmentRooms.cs:10589). It travels TANGENTIALLY, along
    /// <c>cross(up, ToClearing)</c> ≈ (+0.985, 0, −0.174), which is the direction that keeps its
    /// distance from the player constant — so it neither approaches nor retreats, it simply goes
    /// past. 6.8 m of travel, 3.4 m either side of the anchor.</para>
    ///
    /// <para><b>THE TRUNKS DO THE WORK.</b> 13 m is inside the second trunk band (10.0–15.5 m, 22
    /// trunks of base radius 0.18–0.32 m, :7989) with the first band (6.2–10.0 m, 16 trunks of
    /// 0.23–0.40 m) between it and the player. Over 6.8 m of lateral travel it passes behind several
    /// of them: the player gets three or four separate glimpses of the same thing rather than one
    /// continuous view of it, which is what makes a walking figure read as a walking figure that is
    /// TRYING NOT TO BE SEEN. None of that is authored. It is what happens when a real object walks
    /// behind real trees.</para>
    ///
    /// <para><b>THE GROUND IS FOLLOWED, NOT ASSUMED.</b> At 13 m the forest floor swings through
    /// roughly ±0.3 m (<c>ForestY</c>, :7957 — see the Ground block below). A figure at y = 0 would
    /// wade or float, and at this distance that reads as "the effect is broken" rather than as
    /// anything frightening. The height is therefore sampled per frame along the walk, which also
    /// buys the gait a small rise and fall for free.</para>
    ///
    /// <para><b>THE CAST.</b> Something that walks and is recognisably wrong: a Living Corpse
    /// shambling, a Hound trotting, a Living Bones striding. All base-game.</para>
    ///
    /// <para><b>IT STROLLS NOW — ModBuild 150, and it is the second half of the teleport fix.</b>
    /// The hold was 2.40 s, which put 6.80 m of path into a 4.20 s event: 1.62 m/s, a brisk human
    /// walk, for a corpse. Combined with a <c>RunBlend</c> nailed to 0.55 that was a half-blended
    /// idle played over a full-speed glide, which is precisely what the user reported twice as
    /// "teleportiert sich" (see <c>Clone.Gait</c> for the decompiled evidence and the mapping).
    /// <c>Clone.Gait</c> now matches the legs to whatever speed this event asks for, so the speed
    /// itself became a free choice — and 4.60 s of hold puts the same 6.80 m into 6.40 s, i.e.
    /// 1.06 m/s. A thing that strolls between the trunks is at least as frightening as one that
    /// hurries, it sits comfortably inside every creature's own clip rate (the ModBuild 149 census
    /// implies 1.32–1.83 m/s at full blend), and it buys the trunks more time to do the work the
    /// block above credits them with: more separate glimpses of the same thing rather than one
    /// continuous view. The 83 s slot beat (Haunt.Schedule.cs:73) is two orders above this, so a
    /// longer event cannot collide with the next one.</para>
    ///
    /// <para><b>AND SINCE ModBuild 152 THE STROLL IS THE SLOW CREATURES' ONLY, WHICH IS WHAT THE
    /// PARAGRAPH ABOVE GOT WRONG.</b> "A thing that strolls between the trunks is at least as
    /// frightening as one that hurries" is true of a shambling corpse and false of a wolf, and the
    /// user said so with the wolf in front of him. The path length and the run length are now derived
    /// from the creature's own locomotion clip (see THE CROSSING'S SPEED below): the Living Corpse
    /// keeps this event almost exactly as authored — 7.4 m at 1.16 m/s over the full 6.40 s — and the
    /// Hound covers 12 m at 4.21 m/s in 2.85 s. The 6.80 m and the 6.40 s above are therefore the
    /// REFERENCE the derivation starts from rather than what any creature actually walks.</para>
    /// </summary>
    private static readonly HauntEvent ForestCross = new(
        2, "the thing that passes between the trunks",
        reveal: 1.00f, hold: 4.60f, fade: 0.80f,
        // THE AUTHORED PATH IS NOW A REFERENCE RATHER THAN THE PATH — its CENTRE and its DIRECTION
        // are used verbatim and its LENGTH is replaced per creature. See THE CROSSING'S SPEED below.
        from: new Vector3(-2.26f - 3.4f * 0.985f, 0f, -12.80f - 3.4f * -0.174f),
        to: new Vector3(-2.26f + 3.4f * 0.985f, 0f, -12.80f + 3.4f * -0.174f),
        height: 2.20f,
        runBlend: 0.55f,
        face: Vector3.zero,
        cast: new[] { CClass.ENPCModel.LivingCorpse, CClass.ENPCModel.Hound, CClass.ENPCModel.LivingBones });

    // =============================================================================================
    //  THE CROSSING'S SPEED — DERIVED FROM THE CREATURE, not imposed on it.
    //
    //  USER REPORT, ModBuild 151, verbatim: "Es wird ein Wolf angezeigt der schnell rennt aber die
    //  Geschwindigkeit in der er sich bewegt ist deutlich langsamer, dann mach die Bewegung auch
    //  schneller."
    //
    //  WHAT THE LOG SAID HE WAS LOOKING AT (Player.log:10215, the gait line for 'Hound'): the path
    //  moved it at 1.06 m/s while its own locomotion clip — 0.50 s long at scale 1.833 — covers
    //  4.95 m/s at full blend. Clone.Gait did exactly what it was built to do and bent the animation
    //  to the path: RunBlend 0.60 with Animator.speed 0.63, i.e. a running wolf played at
    //  five-eighths rate while it crawled. THE DESIGN HAD THE DEPENDENCY THE WRONG WAY ROUND. The
    //  path speed was an authored constant (6.80 m over the event's own length) and the creature had
    //  to fit it; it is now the creature that decides and the path that follows.
    //
    //  THE RULE, in the order the arithmetic runs:
    //      want     = implied(creature) * CrossBlendTarget          [the speed the legs read at]
    //      distance = clamp(want * authoredSeconds, MinMetres, MaxMetres)
    //      seconds  = clamp(distance / want, MinSeconds, authoredSeconds)
    //  so the DISTANCE takes the first bite (it is bounded by where the trunks are) and the
    //  DURATION takes what is left. Both bounds can only SHORTEN the event, never lengthen it, which
    //  is what keeps every consumer of the authored length correct without being told: the arming
    //  window in HauntFigures.TickBody is still ev.Seconds x DurationMul, and a figure whose own run
    //  ends early simply has an envelope of 0 for the remainder rather than being cut off.
    //
    //  WHAT IT COMES OUT AT, for the crossing's whole cast (authored length 6.40 s):
    //      Living Corpse  implied 1.36 -> want 1.16 m/s, 7.4 m in 6.40 s   (was 1.06 m/s, 6.8 m)
    //      Living Bones   implied 1.83 -> want 1.56 m/s, 10.0 m in 6.40 s
    //      Hound          implied 4.95 -> want 4.21 m/s, 12.0 m in 2.85 s  (was 1.06 m/s, 6.8 m)
    //  THE HEAVY CREATURES KEEP THEIR STROLL — that was a deliberate ModBuild 150 choice and the
    //  user has not objected to it — and only the fast one moves like itself. The wolf now crosses
    //  in under three seconds, which is also why the event gets SHORTER for it rather than longer:
    //  a wolf that trots for six and a half seconds has stopped being a glimpse.
    // =============================================================================================

    /// <summary>The share of its own implied gait speed a travelling creature is driven at. Near 1
    /// on purpose: <c>Clone.Gait</c> turns the ratio between path speed and implied speed into the
    /// <c>RunBlend</c> weight, so this IS the blend the Idle-Run tree will be held at, and the whole
    /// complaint was a blend of 0.21 dressed up as 0.60 by a clip slowed to 0.63x. Slightly under 1
    /// rather than exactly 1 so <c>Animator.speed</c> never has to exceed 1 to make up a rounding
    /// difference — a clip played faster than authored is the failure this replaces, seen from the
    /// other side.</summary>
    private const float CrossBlendTarget = 0.85f;

    /// <summary>Shortest and longest the crossing's path may be, in room-local metres. The upper
    /// bound is GEOMETRY and not taste: the walk is tangential at a radius of 13.0 m, so 12 m of
    /// path is a sweep of ±24° whose ends sit at 14.3 m — still inside the second trunk band
    /// (10.0–15.5 m, BuildEnvironmentRooms.cs:7989), which is the band the event's whole "several
    /// separate glimpses" design depends on. Past that the figure walks out of the trees it is
    /// supposed to be hiding behind.</summary>
    private const float CrossMinMetres = 5.0f;
    private const float CrossMaxMetres = 12.0f;

    /// <summary>The floor on how long a crossing may take, whatever the creature implies. Nothing in
    /// today's roster reaches it (it would need an implied speed over 5.5 m/s), and it is here so
    /// that a future fast creature cannot turn the event into a frame and a half — the standing brief
    /// asks for "was that there?", which needs a there.</summary>
    private const float CrossMinSeconds = 2.20f;

    /// <summary>
    /// THE CREATURE'S OWN GAIT SPEED AT FULL BLEND, in metres per second — the same quantity
    /// <c>Clone.Gait</c> computes at runtime as <c>StrideMetres * scale / walkClipSeconds</c>, but
    /// available at ARM TIME, which is the whole reason this table exists.
    ///
    /// <para><b>WHY A TABLE AND NOT THE MEASUREMENT.</b> The measurement needs the prefab: the scale
    /// comes from <c>CharacterManager.Height</c> and the clip length from the animator controller,
    /// and neither exists until an asynchronous Addressables load has finished — several frames
    /// AFTER the path has to be decided, because the path decides the event's own length and the
    /// anchor is placed on the arming frame. So the choice is between a table that can be wrong and
    /// a path that cannot depend on the creature at all, which is the defect this round is fixing.</para>
    ///
    /// <para><b>IT IS CHECKED RATHER THAN TRUSTED.</b> <c>Clone.Gait</c> receives this estimate and
    /// prints it beside the value it measured off the real prefab, with the ratio; a table that
    /// drifts from the assets therefore announces itself in the log instead of quietly mis-timing an
    /// event. And a wrong entry is bounded rather than dangerous: the path is already fixed by then,
    /// so <c>Gait</c> simply blends the animation to it exactly as it does today.</para>
    ///
    /// <para><b>EVERY NUMBER IS FROM A HARDWARE CENSUS, none is invented.</b> Scale and clip are the
    /// <c>HAUNT FIGURES CENSUS</c> lines: Hound 1.833 with <c>Hound_Move_v003</c> 0.50 s and Cultist
    /// 1.300 with <c>Cultist_Walk_v001</c> 1.00 s (ModBuild 151, Player.log:10216 and :7661); Living
    /// Corpse 0.878/0.87 s, Living Bones 1.258/0.93 s and High Cultist 1.636/1.67 s (ModBuild 149,
    /// quoted in <c>Clone.Gait</c>'s own doc). The clip picked here is the one
    /// <c>Clone.WalkClipSeconds</c> would pick — same names, same order.</para>
    /// </summary>
    private static float ImpliedSpeed(CClass.ENPCModel model) => model switch
    {
        CClass.ENPCModel.Hound => 4.95f,          // 1.35 x 1.833 / 0.50
        CClass.ENPCModel.LivingBones => 1.83f,    // 1.35 x 1.258 / 0.93
        CClass.ENPCModel.Cultist => 1.76f,        // 1.35 x 1.300 / 1.00
        CClass.ENPCModel.LivingCorpse => 1.36f,   // 1.35 x 0.878 / 0.87
        CClass.ENPCModel.HighCultist => 1.32f,    // 1.35 x 1.636 / 1.67
        // Never censused (it has only ever played a STANDING event, where none of this is read).
        // The fallback is the stride at scale 1 over a one-second cycle, i.e. exactly what
        // Clone.WalkClipSeconds falls back to.
        _ => 1.35f,
    };

    // ---- the takeover set ---------------------------------------------------------------------------

    /// <summary>
    /// Which of the room's cards this lane was DESIGNED to take over. Stated once, here; the
    /// suppression mask, the log line and the event lookup are all derived from it, never typed
    /// again.
    ///
    /// <para>To suppress a card WITHOUT replacing it — should the user decide that one of the
    /// remaining shader apparitions should simply stop happening — adding its index here and giving
    /// <see cref="EventFor"/> an event with an empty cast is the whole change: the mask would then
    /// never include it (because <see cref="IsMine"/> requires a castable creature) and the card
    /// would keep being drawn. Making it stop entirely instead is a one-line change to
    /// <see cref="MaskFor"/>, and is called out here so that decision is a decision rather than an
    /// archaeology exercise.</para>
    /// </summary>
    /// <para><b>THE FOREST INDICES MOVED IN ModBuild 147</b> — they were 2 and 3 and are now 1 and 2.
    /// The wood lost three of its six cards when the hand-built apparition figures were deleted on
    /// the user's order, and its catalogue was renumbered rather than left with holes: a card index
    /// is a POSITION in the bake's catalogue, and the schedule's group partition reads a contiguous
    /// count. The cellar's 0 and 4 are unchanged, because the cellar kept six cards.</para>
    private static bool IsMineByDesign(SkyStyle style, int card) =>
        style == SkyStyle.Cellar ? card == 0 || card == 4
                                 : card == 1 || card == 2;

    // =============================================================================================
    //  THE APPARITION ORDINAL — "how many figure slots has this room had, counting from a fixed
    //  point". It is what Roster.Pick iterates its shuffled cast with, and the reason it exists is
    //  in that method's own block: successive apparitions are about THREE slots apart, three is the
    //  cast size, so a shuffle indexed by the SLOT lands on the same position of the next block
    //  about a third of the time and measures out no better than the independent draw it replaces.
    //  Indexed by this, consecutive apparitions cannot repeat at all.
    //
    //  IT COUNTS CARDS AND NOT APPEARANCES, deliberately, and that is the multiplayer property. A
    //  slot's CARD is decided by the schedule's group partition — a function of the slot index and
    //  nothing else. A slot's LIVENESS additionally reads the frequency dial and the element channel,
    //  and the dial is the one shared value that can differ between two peers for the frame it is
    //  being moved. So this counts what the partition owns and lets the dial thin the sequence out.
    // =============================================================================================

    /// <summary>
    /// MIRROR of the card partition in <c>Haunt.Resolve</c> (Haunt.Schedule.cs:188-198) — the four
    /// lines that turn a slot index into a card index, without the liveness test, the jitter or the
    /// force override that surround them there.
    ///
    /// <para><b>WHY A MIRROR AND NOT THE CALL.</b> <c>Haunt.Resolve</c> answers for ONE moment: it
    /// takes a clock rather than a slot, it folds in the element gains and the dial, and — decisively
    /// — it returns the FORCED card for every input while an Advanced-menu test is latched. Walking
    /// it backwards over past slots would therefore answer "every slot was the forced card", which is
    /// not what this counts. The partition itself is four lines of exact integer arithmetic and one
    /// hash channel, and it is the only part of that method this needs.</para>
    ///
    /// <para><b>WHAT A DRIFT COSTS, because this is the fourth copy of that arithmetic in the repo
    /// (the cginc, the bake, Haunt.Schedule.cs and here).</b> Nothing that can be seen as a fault: a
    /// wrong count produces a DIFFERENT deterministic order of the same creatures, identically on
    /// every client, and at worst a few more repeats. It cannot desync two peers, cannot draw a
    /// creature an event was not designed for, and cannot change WHEN anything happens — the schedule
    /// this feature actually obeys is still <c>Haunt.Resolve</c>'s and is not touched here. The one
    /// number that must stay in step is the hash CHANNEL: 1 is <c>HcPick</c>.</para>
    /// </summary>
    private static int CardOfSlot(SkyStyle style, float slot)
    {
        float grp = slot - 3f * Mathf.Floor(slot / 3f);
        float inGroup = Mathf.Max(Mathf.Floor(Haunt.CardsIn(style) / 3f + 0.5f), 1f);
        float j = Mathf.Min(Mathf.Floor(Haunt.Hash(slot, 1f) * inGroup), inGroup - 1f);
        return (int)(grp + 3f * j);
    }

    /// <summary>How far back the ordinal counts. It restarts on a fixed boundary rather than running
    /// from slot 0 for ever, so the cost of one arm is bounded no matter how long the shared clock
    /// has been running: 4096 slots is 94 hours at the 83 s beat, and the whole loop is one hash and
    /// one compare per slot. The price is a single potential repeat at each boundary, i.e. one per
    /// four days of continuous play — against the alternative, which is an unbounded loop that a
    /// shared epoch nobody in this file controls could make arbitrarily long.</summary>
    private const int OrdinalChunkSlots = 4096;

    private static float _ordCached = -1f;
    private static float _ordSlot = float.NaN;
    private static SkyStyle _ordStyle = SkyStyle.Default;

    /// <summary>The ordinal for this slot: how many of this room's figure-card slots precede it
    /// since the last chunk boundary. Memoised because <see cref="Arm"/> can be re-entered on every
    /// frame of a slot it has refused (a cast that will not resolve, a path that crosses masonry),
    /// and a 4096-step loop at 90 Hz is a cost nothing else in this feature has. The memo is a cache
    /// of a pure function and never a decision.</summary>
    private static float ApparitionOrdinal(SkyStyle style, float slotIndex)
    {
        float slot = Mathf.Max(Mathf.Floor(slotIndex), 0f);
        if (_ordCached >= 0f && _ordStyle == style && _ordSlot.Equals(slot))
            return _ordCached;

        float from = Mathf.Floor(slot / OrdinalChunkSlots) * OrdinalChunkSlots;
        float n = 0f;
        for (float m = from; m < slot; m += 1f)
            if (IsMineByDesign(style, CardOfSlot(style, m)))
                n += 1f;

        _ordCached = n;
        _ordSlot = slot;
        _ordStyle = style;
        return n;
    }

    /// <summary>
    /// True when this lane, rather than <c>EnvHaunt.shader</c>, actually plays this card RIGHT NOW
    /// on THIS machine — design intent AND a creature that resolved.
    ///
    /// <para><b>THE ROSTER TEST IS PART OF THE PREDICATE, AND THAT IS THE WHOLE SAFETY PROPERTY.</b>
    /// The suppression mask is derived from this same function, so a card can never be suppressed
    /// without being replaceable, nor replaced without being suppressed. If a machine cannot resolve
    /// any of an event's cast — a trimmed install, an asset system that has not finished coming up —
    /// that card is simply not ours, the mask does not claim it, and the player sees the
    /// shader-drawn apparition exactly as before.</para>
    /// </summary>
    private static bool IsMine(SkyStyle style, int card) =>
        IsMineByDesign(style, card) && Roster.CanCast(EventFor(style, card).Cast);

    /// <summary>
    /// How long this card's event actually LASTS when a figure plays it, in shared-clock seconds —
    /// or 0 when the card is not a figure card on this machine.
    ///
    /// <para>WHY IT IS PUBLIC. <c>Haunt.ForceLoopSeconds</c> decides how often a LATCHED test trigger
    /// re-anchors, and it derives that from <c>CardSeconds</c> — the SHADER card's authored
    /// reveal+hold+fade. For a card a figure has taken over, those two numbers are unrelated: the
    /// shader's forest card 3 is 0.34 s while the figure's crossing runs 4.2 s. The result, visible
    /// in the ModBuild 146 hardware log, is a forced test that re-anchors NINE TIMES without the
    /// figure ever finishing its walk — i.e. the one tool the user has for looking at these events
    /// could not show him a whole one. The loop has to be the length of the thing that is actually
    /// drawn, so the side that knows it has to say.</para>
    ///
    /// <para><b>IT IS THE AUTHORED LENGTH AND THEREFORE AN UPPER BOUND, which is the only answer this
    /// signature can honestly give.</b> Since ModBuild 152 a crossing's real length depends on which
    /// creature was cast (see THE CROSSING'S SPEED) — the Hound runs 2.85 s where the Living Corpse
    /// runs 6.40 s — and this is asked WITHOUT a slot, from <c>Haunt.ForceLoopSeconds</c>, sometimes
    /// before anything is armed. Answering with the authored maximum makes a latched test loop wait
    /// out the SLOWEST creature's run before it re-anchors, which is a slightly longer gap for a fast
    /// one and never a run that gets cut off. The alternative — resolving the creature for the slot
    /// in here — would make a diagnostic helper a second consumer of the cast permutation for no gain
    /// the tester can see.</para>
    /// </summary>
    internal static float FigureSeconds(SkyStyle style, int card)
    {
        if (!IsMine(style, card))
            return 0f;
        return EventFor(style, card).Seconds;
    }

    /// <summary>The bitmask published as <c>_GhvrHauntFigures.x</c> — derived from
    /// <see cref="IsMine"/> rather than typed, for the reason above.</summary>
    private static float MaskFor(SkyStyle style)
    {
        int mask = 0;
        for (int c = 0; c < Haunt.EventCount; c++)
            if (IsMine(style, c))
                mask |= 1 << c;
        return mask;
    }

    private static string CardList(SkyStyle style)
    {
        var sb = new System.Text.StringBuilder(48);
        for (int c = 0; c < Haunt.EventCount; c++)
        {
            if (!IsMine(style, c))
                continue;
            if (sb.Length > 0) sb.Append(", ");
            sb.Append(c).Append(" (").Append(EventFor(style, c).Name).Append(')');
        }
        return sb.Length > 0 ? sb.ToString() : "none";
    }

    private static HauntEvent EventFor(SkyStyle style, int card) =>
        style == SkyStyle.Cellar ? (card == 0 ? CellarWindow : CellarStair)
                                 : (card == 1 ? ForestWatcher : ForestCross);

    // =============================================================================================
    //  THE WALL GATE — a figure's path may not cross masonry, and it is CHECKED rather than argued.
    //
    //  USER REPORT that produced it, verbatim: "Die figuren sollten nicht durch wände glitchen."
    //  The stair walk really did, twice per run (see CellarStair for the arithmetic), and the reason
    //  it shipped is instructive: its doc comment contained a correct-sounding sentence — "everything
    //  left and right of the shaft's own side walls is solid room" — which was simply not true of the
    //  numbers on the next line. NO AMOUNT OF PROSE CATCHES THAT. Coordinates in this file are typed
    //  by hand from a bake that is 11 000 lines long and is edited by other lanes; the only thing
    //  that can keep a path honest is arithmetic that runs.
    //
    //  WHY RUNTIME AND NOT BAKE-TIME. The bake is where the geometry is, and a gate there would be
    //  the stronger place — but the PATHS are here, in src/, and unity/ is owned by other lanes this
    //  round. A check that lives beside the numbers it checks cannot be half-updated; a check on the
    //  other side of a lane boundary can. It costs one pass over four planes per apparition, at arm
    //  time, on a frame that has just started an asset load.
    //
    //  WHAT IT DOES ON A HIT: the event is REFUSED — one warning naming the wall and the crossing
    //  point, and the slot is quiet. Not an exception (this feature never throws at the game) and not
    //  a clamp (a path silently moved is a design nobody reviewed). A quiet slot is the honest answer
    //  and the schedule tries again in 83 seconds.
    // =============================================================================================

    /// <summary>
    /// One vertical slab of masonry, as a plane plus the rectangle of it that is actually solid.
    /// Room-local, axis-aligned, cellar only — the forest has no walls at all, which is why
    /// <see cref="PathCrossesWall"/> answers "no" for it in one compare.
    /// </summary>
    private readonly struct WallPlane
    {
        /// <summary>0 = the plane is x = <see cref="At"/>, 2 = the plane is z = <see cref="At"/>.
        /// There is no y case: no figure in either room passes through a floor or a ceiling, and a
        /// third axis would be a branch nothing exercises.</summary>
        internal readonly int Axis;

        internal readonly float At;

        /// <summary>Extent along the OTHER horizontal axis, and vertically.</summary>
        internal readonly float Lo, Hi, YLo, YHi;

        /// <summary>The hole in it, in the same two coordinates, or all-zero for a solid slab. A
        /// crossing INSIDE the hole is legal — that is a doorway, not a glitch.</summary>
        internal readonly float HoleLo, HoleHi, HoleYLo, HoleYHi;

        internal readonly string Name;

        internal WallPlane(int axis, float at, float lo, float hi, float yLo, float yHi, string name,
                           float holeLo = 0f, float holeHi = 0f, float holeYLo = 0f, float holeYHi = 0f)
        {
            Axis = axis; At = at; Lo = lo; Hi = hi; YLo = yLo; YHi = yHi; Name = name;
            HoleLo = holeLo; HoleHi = holeHi; HoleYLo = holeYLo; HoleYHi = holeYHi;
        }
    }

    /// <summary>
    /// The cellar's masonry, MIRRORED from the bake with each line cited. Room extents are
    /// <c>CW = 10.5, CD = 9.0, CH = 3.3</c> (BuildEnvironmentRooms.cs:2116), so the walls stand at
    /// x = ±5.25 and z = ±4.50.
    ///
    /// <para>This is a mirror and carries the same debt every other mirror in this feature carries
    /// (see the Ground block): <c>scripts/check-mirrors.sh</c> cannot compare a C# array here against
    /// geometry generated under <c>unity/</c>, so the guard is this comment plus the cited lines. The
    /// failure mode if the bake moves a wall and this does not follow is BENIGN IN THE DIRECTION THAT
    /// MATTERS — a stale plane can only refuse an event that would have been fine, never admit one
    /// that walks through stone, because every event in this file is checked against ALL of them.</para>
    /// </summary>
    private static readonly WallPlane[] CellarWalls =
    {
        // North wall, inner face. The window is the hole: snapped opening x −2.068…−0.636,
        // y 2.200…2.986 (BuildEnvironmentRooms.cs:3197-3212, printed at bake time).
        new(2, 4.50f, -5.25f, 5.25f, 0f, 3.30f, "the north wall (the window wall)",
            -2.068f, -0.636f, 2.200f, 2.986f),
        // West wall. The hole is the stair doorway, SNAPPED (z 1.658…3.237, up to y 2.357) — the
        // snapped rect and not StairHole itself, for the reason the bars read it: WallMesh keeps or
        // drops whole 0.16 m cells (:2539-2550, :8844-8845).
        new(0, -5.25f, -4.50f, 4.50f, 0f, 3.30f, "the west wall (the stair wall)",
            1.658f, 3.237f, 0f, 2.357f),
        // The two side walls of the stair alcove, and its black end cap. BuildShaft(2.2, 2.6, 1.6) is
        // placed at (−5.25, 0, −hd + StairHole.xMin) = (−5.25, 0, 1.70), so the shaft's interior is
        // x −7.45…−5.25, z 1.70…3.30, y 0…2.60 (:3556-3559, :6849-6870); the cap is at x = −7.40
        // (:3563-3567). THESE ARE THE TWO THE OLD STAIR WALK WENT THROUGH.
        new(2, 1.70f, -7.45f, -5.25f, 0f, 2.60f, "the stair alcove's south side wall"),
        new(2, 3.30f, -7.45f, -5.25f, 0f, 2.60f, "the stair alcove's north side wall"),
        new(0, -7.40f, 1.70f, 3.30f, 0f, 2.60f, "the stair alcove's black end cap"),
        // The other two room walls, for completeness: nothing is authored near them today, which is
        // exactly the state in which a future event gets placed carelessly.
        new(2, -4.50f, -5.25f, 5.25f, 0f, 3.30f, "the south wall"),
        new(0, 5.25f, -4.50f, 4.50f, 0f, 3.30f, "the east wall"),
    };

    /// <summary>
    /// Does this event's path pass through masonry? Returns the wall's name, or null.
    ///
    /// <para>The test is on the SEGMENT and is exact rather than sampled: a straight walk crosses an
    /// axis-aligned plane at most once, at a fraction that solves for one coordinate, so the crossing
    /// point is computed and tested against the slab's rectangle and its hole. Sampling would be the
    /// obvious implementation and is strictly worse — it can step over a 5 cm jamb.</para>
    ///
    /// <para>A path that does not move cannot cross anything and is answered in the first compare,
    /// which is what three of the four events are since this round.</para>
    /// </summary>
    private static string? PathCrossesWall(SkyStyle style, Vector3 from, Vector3 to)
    {
        if (style != SkyStyle.Cellar || from == to)
            return null;

        for (int i = 0; i < CellarWalls.Length; i++)
        {
            WallPlane w = CellarWalls[i];
            float a = w.Axis == 0 ? from.x : from.z;
            float b = w.Axis == 0 ? to.x : to.z;
            float da = a - w.At, db = b - w.At;
            if (da == 0f || db == 0f || (da > 0f) == (db > 0f))
                continue;                                  // both ends on the same side: no crossing

            float t = da / (da - db);
            Vector3 p = Vector3.Lerp(from, to, t);
            float u = w.Axis == 0 ? p.z : p.x;             // the in-plane horizontal coordinate
            if (u < w.Lo || u > w.Hi || p.y < w.YLo || p.y > w.YHi)
                continue;                                  // it passes the plane beyond the slab

            bool throughHole = w.HoleHi > w.HoleLo
                               && u >= w.HoleLo && u <= w.HoleHi
                               && p.y >= w.HoleYLo && p.y <= w.HoleYHi;
            if (throughHole)
                continue;                                  // a doorway is not a glitch

            return $"{w.Name} at {(w.Axis == 0 ? "x" : "z")} = {w.At:F2}, crossed at room-local "
                   + $"({p.x:F2}, {p.y:F2}, {p.z:F2})";
        }

        return null;
    }

    // =============================================================================================
    //  ARM → DRIVE → RETIRE. The life of one apparition.
    // =============================================================================================

    /// <summary>The node the figure hangs under, named <c>Haunt&lt;card&gt;</c>.</summary>
    private static GameObject? _anchor;

    /// <summary>Which way round the walk runs this time — a per-slot hash, so both clients agree.</summary>
    private static bool _reversed;

    /// <summary>
    /// The (card, start clock) pair of the last run <see cref="Arm"/> refused, so the reason is
    /// logged ONCE per run instead of once per frame.
    ///
    /// <para>THIS IS A DEFECT FIX AND NOT A TIDY-UP. When Arm bails it clears <c>_card</c>, and the
    /// driver's next frame sees <c>_card &lt; 0</c> with the slot's window still open and arms again
    /// — so a slot that cannot be cast, or a path that crosses a wall, wrote a log line at the frame
    /// rate for as long as the window lasted. At 90 Hz over a 5.5 s window that is five hundred
    /// copies of the same sentence, which is how a log stops being readable. The pair is unique per
    /// run, so a genuine second refusal (the next slot, or the next loop of a latch) still speaks.</para>
    /// </summary>
    private static int _quietCard = -1;
    private static float _quietStart = float.NaN;

    /// <summary>True the first time this exact run is refused; false for every repeat of it.</summary>
    private static bool AnnounceQuiet(int card)
    {
        if (_quietCard == card && _quietStart.Equals(_startClock))
            return false;
        _quietCard = card;
        _quietStart = _startClock;
        return true;
    }

    /// <summary>Resolved once at arm time and then held, so the figure cannot change species or
    /// facing mid-event if anything about the resolve ever became time-dependent.</summary>
    private static string _model = string.Empty;

    private static Quaternion _standRot = Quaternion.identity;

    /// <summary>THIS RUN'S path, in room-local metres — the authored one for a figure that stands,
    /// and the creature-derived one for a figure that travels (see THE CROSSING'S SPEED). Everything
    /// that positions the anchor reads these and not <c>ev.From</c>/<c>ev.To</c>, so there is exactly
    /// one place the two can differ.</summary>
    private static Vector3 _runFrom, _runTo;

    /// <summary>THIS RUN'S envelope multiplier: the schedule's <c>DurationMul</c> for a figure that
    /// stands, and <c>runSeconds / ev.Seconds</c> for one whose crossing was shortened to suit its
    /// own gait. It scales reveal, hold and fade TOGETHER, so a shorter run is the same shape played
    /// faster rather than a differently-shaped event — and it is never greater than
    /// <c>DurationMul</c>, which is what keeps the arming window in <see cref="TickBody"/> a valid
    /// upper bound without that side having to know any of this.</summary>
    private static float _shapeMul = 1f;

    /// <summary>
    /// Open the event: create the anchor node the audio cue looks for, decide the creature and the
    /// direction from the shared clock, and ask the clone factory to start loading. Nothing is
    /// visible yet — <see cref="ArmLeadSeconds"/> seconds of head start is the whole point.
    ///
    /// <para><b>THE ANCHOR NODE IS THE AUDIO INTEGRATION, AND IT IS THE ONLY ONE.</b>
    /// <c>EnvSound.HauntPosition</c> (EnvSound.cs:1001-1022) already looks for a descendant of the
    /// room root named exactly <c>Haunt0</c>…<c>Haunt5</c> and plays that card's cue from its
    /// renderer bounds — its doc comment says in as many words that it was written as a seam for
    /// "another lane rebuilding all twelve apparitions as real 3D geometry in this same round", and
    /// this is that lane. So the cue lands on the figure, and it FOLLOWS the figure as it walks,
    /// with not one line of coupling between the two files.</para>
    ///
    /// <para><b>IT IS CREATED PER EVENT AND DESTROYED WITH IT, deliberately.</b> A permanent set of
    /// <c>Haunt0</c>/<c>Haunt4</c> nodes would be cheaper, but <c>HauntPosition</c>'s SECOND
    /// fallback is "any descendant whose name starts with Haunt", and a permanent node would
    /// therefore capture the cues of the cards this lane does NOT own — silently moving the
    /// handprints' and the bookshelf's sounds onto the window. Existing only during our own slot
    /// leaves every other card's behaviour byte-identical to today's.</para>
    /// </summary>
    private static void Arm(SkyStyle style, int card, float slotIndex)
    {
        HauntEvent ev = EventFor(style, card);

        // WHICH WAY ROUND — hash channel 10. Channels 0/1/3/4/5/6/7 are the schedule's own
        // (Haunt.Schedule.cs), 2 is EnvSound's per-event variation and 13 is the rat's stare, so
        // 9/10/11 are this feature's and nothing else reads them. Deterministic, therefore shared.
        _reversed = Haunt.Hash(slotIndex, 10f) >= 0.5f;

        // WHICH CREATURE — a PERMUTATION of the cast, iterated by the APPARITION ORDINAL rather than
        // drawn from a hash of the slot. See Roster.Pick for the shuffle and for why consecutive
        // apparitions can never repeat, and ApparitionOrdinal for why it is not the slot index. Both
        // are pure functions of the shared clock's slot, so two clients cannot disagree.
        float ordinal = ApparitionOrdinal(style, slotIndex);
        _model = Roster.Pick(ev.Cast, ordinal, out CClass.ENPCModel picked);
        if (_model.Length == 0)
        {
            // Nothing in this event's cast is available. ONE line, and the slot is simply quiet —
            // the mask has already suppressed the shader card for this room, so the honest outcome
            // is a quiet slot rather than a substitute creature that was never designed for the
            // framing. The next slot tries again. ONE line per RUN and not per frame — see
            // AnnounceQuiet for why that guard had to be added.
            if (AnnounceQuiet(card))
                VRLog.Info("Core", $"HAUNT FIGURES: {style} card {card} ({ev.Name}) is quiet this slot — none of "
                               + $"its cast ({Roster.Describe(ev.Cast)}) resolved to a base-game enemy prefab "
                               + "on this machine. No apparition rather than a wrong one.");
            _card = -1;
            return;
        }

        // ---- THIS RUN'S PATH AND THIS RUN'S LENGTH, derived from the creature ---------------------
        //
        // See THE CROSSING'S SPEED above CrossBlendTarget for the rule and for the user report that
        // produced it. A figure that stands keeps the authored path and the authored length exactly;
        // a figure that travels keeps the authored path's CENTRE and DIRECTION and gets a length of
        // its own. Both bounds can only shorten the event, never lengthen it.
        float authoredSeconds = Mathf.Max(ev.Seconds * _durMul, 0.01f);
        float implied = ImpliedSpeed(picked);
        float speed = 0f;
        if (ev.From == ev.To)
        {
            _runFrom = ev.From;
            _runTo = ev.To;
            _shapeMul = _durMul;
        }
        else
        {
            Vector3 centre = (ev.From + ev.To) * 0.5f;
            Vector3 along = ev.To - ev.From;
            along.y = 0f;
            Vector3 unit = along.sqrMagnitude > 1e-6f ? along.normalized : Vector3.forward;

            float want = Mathf.Max(implied * CrossBlendTarget, 0.05f);
            float metres = Mathf.Clamp(want * authoredSeconds, CrossMinMetres, CrossMaxMetres);
            float runSeconds = Mathf.Clamp(metres / want, CrossMinSeconds, authoredSeconds);

            _runFrom = centre - unit * (metres * 0.5f);
            _runTo = centre + unit * (metres * 0.5f);
            _shapeMul = runSeconds / Mathf.Max(ev.Seconds, 0.01f);
            speed = metres / runSeconds;
        }

        // THE WALL GATE, ON THE PATH THAT WILL ACTUALLY BE WALKED. See the block above CellarWalls
        // for why this is arithmetic and not a comment: the event it exists to catch shipped behind a
        // doc paragraph that asserted the opposite of what its own coordinates did. It is checked
        // AFTER the derivation above rather than before it, because a derived path is longer than the
        // authored one and a gate on the authored one would be a gate on a path nobody walks.
        // Refused, not clamped — the slot is quiet and the schedule tries again.
        string? wall = PathCrossesWall(style, _runFrom, _runTo);
        if (wall != null)
        {
            if (AnnounceQuiet(card))
                VRLog.Warn("Core", $"HAUNT FIGURES: {style} card {card} ({ev.Name}) is REFUSED — its path from "
                               + $"room-local {_runFrom:F2} to {_runTo:F2} passes through {wall}. A figure may "
                               + "not walk through masonry (user, verbatim: \"Die figuren sollten nicht durch "
                               + "wände glitchen\"), so this slot is quiet rather than showing it. The path is "
                               + "authored in HauntFigures.Events.cs — with its LENGTH derived from the "
                               + "creature since ModBuild 152 — and the walls are mirrored from "
                               + "BuildEnvironmentRooms.cs — if the bake moved a wall, that mirror is what "
                               + "needs to follow.");
            _card = -1;
            return;
        }

        _anchor = new GameObject("Haunt" + card);
        _anchor.transform.SetParent(_room, worldPositionStays: false);
        Vector3 start = PathAt(style, 0f);
        _anchor.transform.localPosition = start;

        // FACING. Three cases, all resolved ONCE here, in room-local space, and never touched
        // again: an authored direction if the event names one (the window figure looks INTO the
        // room, the stair figure looks OUT through its doorway), otherwise "toward the clearing"
        // for a figure that stands where nothing was authored (the forest watcher), otherwise "the
        // way you walk" for one that travels.
        // NOTHING IN THIS FEATURE MAY EVER RE-ORIENT WITH HEAD MOVEMENT (permanent project rule):
        // there is no camera read anywhere in this file, and a facing derived from the walk cannot
        // acquire one by accident.
        Vector3 dir = ev.From == ev.To
            ? (ev.Face != Vector3.zero ? ev.Face : new Vector3(-ev.From.x, 0f, -ev.From.z))
            : (_reversed ? _runFrom - _runTo : _runTo - _runFrom);
        dir.y = 0f;
        _standRot = dir.sqrMagnitude > 1e-6f
            ? Quaternion.LookRotation(dir.normalized, Vector3.up)
            : Quaternion.identity;
        _anchor.transform.localRotation = _standRot;

        // THE ROOM ROOT RIDES ALONG, and only for its LIGHT. The clone factory reads the room's
        // baked rig (_AmbUp/_DirDir/_L*Pos, written per material by BuildEnvironmentRooms.ApplyRig)
        // off one of its materials so the apparition can be lit by the same moon and the same
        // candles as the wall behind it — see the Lighting block in HauntFigures.Clone.cs for why
        // that is read back rather than mirrored, and why it is delivered as per-renderer SH rather
        // than as real Unity lights. The style goes with it because the two rooms answer the element
        // channel differently and _GhvrIndoor is what tells them apart on the GPU side.
        Clone.Request(_model, picked, ev, _anchor.transform, _room, style, speed, implied);

        float travel = (PathAt(style, 1f) - start).magnitude;
        float runSecondsLog = ev.Seconds * _shapeMul;
        VRLog.Info("Core", $"HAUNT FIGURES: {style} card {card} ({ev.Name}) armed at shared clock "
                           + $"{_startClock:F2}s for {runSecondsLog:F2}s — model '{_model}' ({picked}), "
                           + (ev.From == ev.To
                                  ? $"STANDING at room-local {start:F2}, facing {_standRot.eulerAngles.y:F0} deg"
                                  : $"walking {(_reversed ? "the other way" : "the authored way")}, room-local "
                                    + $"{start:F2} to {PathAt(style, 1f):F2}"
                                    // THE GAIT NUMBER, and it is here because it is the one thing a
                                    // hardware round can compare against and this file cannot: the
                                    // CLIP's own implied speed is inside an asset bundle, and a
                                    // mismatch between it and the path is foot slide. The census line
                                    // prints the clip lengths beside this one, so a reader has both
                                    // halves in the same log.
                                    + $" — {travel:F2} m in {runSecondsLog:F2}s = {speed:F2} m/s. "
                                    + "SINCE ModBuild 152 THE PATH IS DERIVED FROM THE CREATURE AND "
                                    + "NOT THE OTHER WAY ROUND (user: \"dann mach die Bewegung auch "
                                    + $"schneller\"): this one implies {implied:F2} m/s at full blend, "
                                    + $"so it is driven at {CrossBlendTarget:F2} of that and the "
                                    + $"authored {(ev.To - ev.From).magnitude:F2} m over "
                                    + $"{ev.Seconds * _durMul:F2}s became {travel:F2} m over "
                                    + $"{runSecondsLog:F2}s, bounded to "
                                    + $"[{CrossMinMetres:F1}, {CrossMaxMetres:F1}] m and at least "
                                    + $"{CrossMinSeconds:F2}s. RunBlend is NO LONGER the authored "
                                    + $"constant it was through ModBuild 149 ({ev.RunBlend:F2} at "
                                    + "every speed, for every creature) and should now land near "
                                    + $"{CrossBlendTarget:F2} — see the HAUNT FIGURES gait line, "
                                    + "which also prints how far the arm-time estimate above was "
                                    + "from the prefab's real numbers")
                           + $". THE CREATURE IS A SHUFFLED ITERATION and no longer a draw: it is "
                           + $"element {(int)ordinal % Mathf.Max(ev.Cast.Length, 1)} of a permutation "
                           + $"of this event's cast ({Roster.Describe(ev.Cast)}) that is reshuffled "
                           + $"every {ev.Cast.Length} apparitions, indexed by APPARITION ORDINAL "
                           + $"{ordinal:F0} (not by slot {slotIndex:F0} — see ApparitionOrdinal for "
                           + "why that distinction is the whole fix) on hash channel 11, while the "
                           + "direction stays a hash of the slot on channel 10. Every creature "
                           + "appears once before any appears twice, no two consecutive apparitions "
                           + "of this room can be the same one, and every input is a pure function of "
                           + "the shared clock's slot — so both clients pick the same creature with "
                           + "ZERO wire traffic and no 'last shown' state exists to drift. Its albedo "
                           + "is multiplied down to the room's own light level while it is up — see "
                           + "the HAUNT FIGURES light level line.");
    }

    /// <summary>
    /// One frame of a running apparition: where it is, which way it faces, how present it is, and
    /// whether it should still exist. All of it is a function of the shared clock and nothing else.
    /// </summary>
    private static void Drive(SkyStyle style, float clock)
    {
        HauntEvent ev = EventFor(style, _card);
        // _shapeMul AND NOT _durMul: a crossing whose length was cut to suit a fast creature has to
        // spend its envelope over the length it actually runs, or the figure would still be at half
        // presence when its walk has finished. They are the same number for every standing event and
        // for any creature whose gait does not shorten the run. See _shapeMul.
        float len = Mathf.Max(ev.Seconds * _shapeMul, 0.05f);
        float t = clock - _startClock;

        // Before the start the figure is loading and MUST NOT be visible: the anchor exists (so the
        // audio cue can find it) but presence is 0, which the clone factory reads as "stay hidden".
        float u = Mathf.Clamp01(t / len);
        float presence = Envelope(t, ev, _shapeMul) * EdgeFade(t, ev, len);

        // ---- THE NO-BACKWARDS-STEP INTERLOCK ---------------------------------------------------
        //
        // TWO GUARDS, BOTH OF WHICH SET PRESENCE TO ZERO — i.e. both of which switch the RENDERERS
        // OFF (Clone.Shade), because "not drawn" is the only honest way to express "it is not there
        // yet". The whole argument, including the measured margin the envelope already provides, is
        // in the block at HauntFigures._quietUntil.
        //
        //  1. A RESTARTED RUN IS BLANKED. The loop moves _startClock forward, so the anchor snaps
        //     from the end of the path back to its start in one frame; nothing may be drawn across
        //     that frame or for a few after it.
        //  2. A RUN NEVER GOES BACKWARDS. Within one run u = t/len and the clock only moves forward,
        //     so this can only fire if that construction is ever broken — and if it is, the figure
        //     is hidden for that frame rather than being drawn behind where it was.
        //
        // The ANCHOR is moved either way, deliberately: the audio cue follows the anchor and the
        // event's sound belongs to where the thing IS, not to where it was last drawn.
        if (clock < _quietUntil || (_lastDrivenU >= 0f && u < _lastDrivenU - 1e-4f))
            presence = 0f;
        else
            _lastDrivenU = u;

        if (_anchor != null)
            _anchor.transform.localPosition = PathAt(style, u);

        Clone.Drive(presence, ev.RunBlend);
    }

    /// <summary>
    /// The presence envelope — the C# twin of <c>GhvrHauntEnvelope</c> (EnvHaunt.cginc:310), kept
    /// deliberately identical in SHAPE so a figure and the shader apparitions in the same room read
    /// as one family: a smoothstep up over <c>reveal</c>, a hold, and either a smoothstep down or,
    /// when <c>fade</c> is zero, a hard step. The hard step is not an optimisation — it is the
    /// instant vanish the watcher is built around, and the cginc's own comment explains why it must
    /// be a real step rather than a collapsed smoothstep.
    ///
    /// <para>It is a TWIN and not a mirror: nothing depends on the two agreeing to the bit, because
    /// they never shade the same pixel. That is why this one is allowed to be a re-implementation
    /// while <see cref="Haunt.Resolve"/> is held to being character-for-character the shader's.</para>
    /// </summary>
    private static float Envelope(float t, in HauntEvent ev, float mul)
    {
        float r = Mathf.Max(ev.Reveal * mul, 1e-4f);
        float h = ev.Hold * mul;
        float f = ev.Fade * mul;
        if (t <= 0f)
            return 0f;
        float up = Mathf.SmoothStep(0f, 1f, Mathf.Clamp01(t / r));
        float down = f > 1e-4f
            ? Mathf.SmoothStep(0f, 1f, Mathf.Clamp01((r + h + f - t) / f))
            : (t <= r + h ? 1f : 0f);
        return Mathf.Clamp01(up * down);
    }

    /// <summary>
    /// A SHORT APPEARANCE AND A SHORT DISSOLUTION THAT NO EVENT CAN AUTHOR AWAY.
    ///
    /// <para><b>USER REPORT, ModBuild 150, verbatim:</b> "Das Verschwinden und Auftauchen der Figuren
    /// geschieht aktuell abrupt von einem Frame auf den anderen. Ich hätte gerne eine kurze
    /// Erscheinen- bzw. Auflösen-Animation."</para>
    ///
    /// <para><b>THE DISAPPEARANCE HALF IS LITERAL AND IT IS IN THIS FILE.</b> Two of the four events
    /// are authored <c>fade: 0.00f</c> — the cellar stair figure (:288) and the treeline watcher
    /// (:326) — and <see cref="Envelope"/> honours that with a real step
    /// (<c>t &lt;= r + h ? 1f : 0f</c>), which was a deliberate design choice recorded as "the instant
    /// vanish the watcher is built around". The user has now looked at it on hardware and asked for
    /// the opposite, so the step goes: this multiplier gives every figure at least
    /// <see cref="EdgeSeconds"/> of dissolve whatever its event says. The SHADER-drawn apparitions
    /// keep their instant vanish — <c>GhvrHauntEnvelope</c> is untouched — because nothing about them
    /// was reported.</para>
    ///
    /// <para><b>IT ONLY EVER SHORTENS THE FIGURE'S PRESENCE, NEVER LENGTHENS THE EVENT.</b> It is a
    /// multiplier in 0..1 applied on top of the envelope, and its ramps are clamped to a third of the
    /// run so a very short slot cannot end up as nothing but edges. An event that already fades over
    /// 0.60 s or 0.80 s is unaffected in practice: its own envelope is below this ramp for the whole
    /// overlap.</para>
    ///
    /// <para><b>WHY 0.35 s AND WHY IT CANNOT READ AS A LOADING BUG.</b> It is comfortably under the
    /// 0.6 s the brief asks for at each end, so it reads as an event rather than as a wait. And it is
    /// a change in BRIGHTNESS of the whole figure at once — the tint is one colour per material
    /// (<c>Clone.Shade</c>) — so there is no moment at which part of the creature is present and part
    /// is not. That is the entire distinction from the ModBuild 148 noise-field dissolve the user read
    /// as half-streamed textures ("viele schwarze flecken in ihnen"), which this must not and does not
    /// resemble: no holes, no marbling, no per-texel anything. The second half of the same fix is
    /// <c>Clone.PerceptualGamma</c>, which stops the rising envelope from spending a third of its
    /// visible change in the first eighth of its time.</para>
    /// </summary>
    private static float EdgeFade(float t, in HauntEvent ev, float len)
    {
        float e = Mathf.Min(EdgeSeconds, len / 3f);
        if (e <= 1e-4f)
            return 1f;
        // The event's own ramps are already at least this long where they exist, so taking the
        // minimum of the two is a no-op there and the whole of the effect where fade is 0.
        float up = Mathf.SmoothStep(0f, 1f, Mathf.Clamp01(t / e));
        float down = Mathf.SmoothStep(0f, 1f, Mathf.Clamp01((len - t) / e));
        return Mathf.Clamp01(up * down);
    }

    /// <summary>The floor on a figure's appearance and dissolution, in seconds, at each end. See
    /// <see cref="EdgeFade"/>.</summary>
    private const float EdgeSeconds = 0.35f;

    /// <summary>Room-local position at walk fraction <paramref name="u"/>, with the forest's ground
    /// followed and the cellar's ignored (the cellar floor undulates by ±6 mm,
    /// BuildEnvironmentRooms.cs:1861 — below the threshold of anything).
    ///
    /// <para>It reads <see cref="_runFrom"/>/<see cref="_runTo"/> — THIS RUN's path — and not the
    /// event's authored one, because a crossing's length is derived from the creature (see THE
    /// CROSSING'S SPEED). The event is no longer a parameter for exactly that reason: it no longer
    /// holds the answer, and a signature that still took it would invite a caller to believe it
    /// did.</para></summary>
    private static Vector3 PathAt(SkyStyle style, float u)
    {
        Vector3 a = _reversed ? _runTo : _runFrom;
        Vector3 b = _reversed ? _runFrom : _runTo;
        Vector3 p = Vector3.Lerp(a, b, Mathf.Clamp01(u));
        if (style == SkyStyle.SwampNight)
            p.y = Ground.ForestY(p.x, p.z);
        return p;
    }

    /// <summary>Drop the running apparition and its anchor. Idempotent.</summary>
    private static void Retire(string why)
    {
        Clone.Release(why);
        if (_anchor != null)
        {
            Object.Destroy(_anchor);
            _anchor = null;
        }
        _card = -1;
        _model = string.Empty;
    }

    // =============================================================================================
    //  THE GROUND — a MIRROR of the forest's height field, and the argument for why it is one.
    // =============================================================================================

    /// <summary>
    /// The forest floor's height at a room-local (x, z).
    ///
    /// <para><b>WHY THIS IS A MIRROR AND NOT A MEASUREMENT.</b> Three ways to know the ground height
    /// under a figure were available and two of them are closed. (1) A RAYCAST needs a collider, and
    /// the room ships none — deliberately, so the hand laser can never catch the environment
    /// (SkyAlternative.cs's collider strip). Adding one would put 30 m of terrain in front of every
    /// pointer in the game. (2) SAMPLING THE GROUND MESH is closed too: reading vertices at runtime
    /// needs <c>Mesh.isReadable</c>, which costs a permanent CPU copy of the mesh, and the bake
    /// turns readability OFF for the assets it imports (BuildEnvironmentRooms.cs:210). (3) So the
    /// height field is mirrored, which is what is left, and it is exact rather than approximate.</para>
    ///
    /// <para><b>WHAT THE MIRROR COSTS, STATED PLAINLY.</b> This is the same class of debt
    /// <c>Haunt.Schedule.cs</c> records for the schedule hash, and the same guard applies: the lint
    /// <c>scripts/check-mirrors.sh</c> cannot cover it (it compares <c>const</c> declarations inside
    /// <c>src/</c>, and the other side of this pair is a private static method under <c>unity/</c>),
    /// so the guard is this comment plus the cited line numbers.
    /// <b>The other side is <c>BuildEnvironmentRooms.cs</c>: <c>ForestY</c> :7957-7981,
    /// <c>PathDist</c> :7942-7952, <c>PathFade</c> :7954-7955, <c>Fbm2</c> :970-979,
    /// <c>Noise2</c> :960-968, <c>Hash3</c> :950-958.</b> Whoever changes the forest's relief must
    /// change this block, and the failure mode if they do not is specific and visible: an apparition
    /// wading through the ground or floating above it at 13 m. It cannot cause a desync, a
    /// mismatch or a crash — every client runs the same mirror.</para>
    ///
    /// <para><b>FLOAT AND THIS ORDER OF OPERATIONS</b>, for the reason the schedule mirror gives:
    /// the bake computes in single precision and reassociating would give a number that is very
    /// nearly right, which is the worst kind.</para>
    /// </summary>
    private static class Ground
    {
        private static bool _logged;

        internal static void Forget() => _logged = false;

        /// <summary>MIRROR of <c>BuildEnvironmentRooms.PathPts</c> :7932-7938 — the crooked path
        /// that leaves the clearing to the south-west, trodden into a shallow hollow.</summary>
        private static readonly Vector2[] PathPts =
        {
            new(0.6f, -1.2f), new(-0.9f, -3.4f), new(-2.6f, -5.2f),
            new(-3.4f, -7.6f), new(-2.7f, -10.3f), new(-3.9f, -12.8f),
            new(-6.4f, -14.6f), new(-9.2f, -15.6f),
        };

        /// <summary>MIRROR of <c>ForestY</c> :7957-7981.</summary>
        internal static float ForestY(float x, float z)
        {
            float r = Mathf.Sqrt(x * x + z * z);
            float lift = Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(1.7f, 4.6f, r)); // dead-flat play space
            float h = lift * (0.44f * Fbm2(x * 0.13f + 19f, z * 0.13f, 3, 981)
                              + 0.15f * Fbm2(x * 0.52f, z * 0.52f, 3, 982) - 0.27f);
            float pd = PathDist(x, z) / 0.95f;
            h -= lift * 0.075f * Mathf.Exp(-pd * pd) * PathFade(x, z);
            h += Mathf.SmoothStep(0f, 1f, Mathf.InverseLerp(19f, 28f, r))
                 * (0.9f + 3.4f * Fbm2(x * 0.145f + 7f, z * 0.145f, 3, 983)
                    * (0.45f + 0.9f * Fbm2(x * 0.055f, z * 0.055f + 21f, 2, 987)));
            if (!_logged)
            {
                _logged = true;
                VRLog.Info("Core", $"HAUNT FIGURES ground mirror live — ForestY({x:F2}, {z:F2}) = {h:F3} m. "
                                   + "This is a documented MIRROR of BuildEnvironmentRooms.cs:7957; the room "
                                   + "ships no colliders and its meshes are not CPU-readable, so a figure's "
                                   + "footing is computed rather than measured. A figure visibly wading or "
                                   + "floating in the forest means this mirror has drifted from the bake.");
            }
            return h;
        }

        /// <summary>MIRROR of <c>PathDist</c> :7942-7952.</summary>
        private static float PathDist(float x, float z)
        {
            var p = new Vector2(x, z);
            float best = float.MaxValue;
            for (int i = 0; i < PathPts.Length - 1; i++)
            {
                Vector2 a = PathPts[i], b = PathPts[i + 1], ab = b - a;
                float t = Mathf.Clamp01(Vector2.Dot(p - a, ab) / Mathf.Max(ab.sqrMagnitude, 1e-4f));
                best = Mathf.Min(best, (a + ab * t - p).magnitude);
            }
            return best;
        }

        /// <summary>MIRROR of <c>PathFade</c> :7954-7955.</summary>
        private static float PathFade(float x, float z) =>
            Mathf.SmoothStep(1f, 0f, Mathf.InverseLerp(9f, 15f, new Vector2(x, z).magnitude));

        /// <summary>MIRROR of <c>Fbm2</c> :970-979.</summary>
        private static float Fbm2(float x, float y, int oct, int seed)
        {
            float acc = 0f, amp = 1f, sum = 0f;
            for (int o = 0; o < oct; o++)
            {
                acc += amp * Noise2(x, y, seed + o * 131);
                sum += amp; amp *= 0.55f; x *= 2.03f; y *= 2.03f;
            }
            return acc / sum;
        }

        /// <summary>MIRROR of <c>Noise2</c> :960-968.</summary>
        private static float Noise2(float x, float y, int seed)
        {
            int x0 = Mathf.FloorToInt(x), y0 = Mathf.FloorToInt(y);
            float tx = x - x0, ty = y - y0;
            tx = tx * tx * (3f - 2f * tx); ty = ty * ty * (3f - 2f * ty);
            float a = Mathf.Lerp(Hash3(x0, y0, 0, seed), Hash3(x0 + 1, y0, 0, seed), tx);
            float b = Mathf.Lerp(Hash3(x0, y0 + 1, 0, seed), Hash3(x0 + 1, y0 + 1, 0, seed), tx);
            return Mathf.Lerp(a, b, ty);
        }

        /// <summary>MIRROR of <c>Hash3</c> :950-958.</summary>
        private static float Hash3(int x, int y, int z, int seed)
        {
            unchecked
            {
                uint n = (uint)(x * 73856093) ^ (uint)(y * 19349663) ^ (uint)(z * 83492791) ^ (uint)(seed * 974711);
                n *= 1274126177u; n ^= n >> 16; n *= 2246822519u; n ^= n >> 13;
                return (n & 0xFFFFFF) / 16777216f;
            }
        }
    }
}
