<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RollbackSource Condition="'$(RollbackSource)' == ''">$(IntermediateOutputPath)Rollback.g.cs</RollbackSource>
  </PropertyGroup>
  <ItemGroup><Compile Include="$(RollbackSource)" /></ItemGroup>
</Project>
