int assertions=0;
void Check(bool value,string message) { assertions++; if(!value) throw new InvalidOperationException(message); }
var a=new CPlayerActor(1); var b=new CPlayerActor(2); var first=new CAbilityCard(11); var next=new CAbilityCard(12);
foreach (bool front in new[]{false,true})
foreach (int seat in new[]{0,1})
{
    var cards=new[]{new CardFixture(),new CardFixture()};
    cards[0].Set(first,front,a); cards[1].Set(next,front,a);
    var source=cards[seat]; var identity=seat==0 ? first : next;
    source.TransferToFlight(identity.CardInstanceID,a);
    Check(!source.Visible && !source.Vanishing,"Flight must immediately replace its source without dock crumble");
    Check(cards[1-seat].Visible,"Unrelated recess must retain its card");
    for(int frame=0;frame<180;frame++)
    {
        source.Set(identity,front,a);
        Check(!source.Visible,"Stale seating must not repaint a departed source, even after the arc duration");
    }
    source.Set(null,front,a);
    Check(!source.Vanishing,"Empty acknowledgement must not create a second departure animation");
    source.Set(identity,front,a);
    Check(source.Visible,"Same card must be reusable after empty acknowledgement");
    source.TransferToFlight(identity.CardInstanceID,a,2);
    source.Set(seat==0 ? next : first,front,a);
    Check(source.Visible,"A new card in the same occupied seat must clear the departure fence");
    source.TransferToFlight((seat==0 ? next : first).CardInstanceID,a,3);
    source.Set(seat==0 ? next : first,front,b);
    Check(source.Visible,"Different actor must not inherit the prior source fence");
}
var unknown=new CardFixture(); unknown.SetAnonymousBack(); unknown.TransferToFlight(int.MinValue,a);
Check(!unknown.Visible,"Covered unknown source must transfer without exposing an identity");
unknown.SetAnonymousBack(); Check(!unknown.Visible,"Stale anonymous snapshot must remain fenced");
unknown.Set(null,false,a); unknown.SetAnonymousBack(); Check(unknown.Visible,"Empty acknowledgement must rearm anonymous seating");
unknown.TransferToFlight(int.MinValue,a,2); unknown.ClearFlightTransfer(); unknown.SetAnonymousBack();
Check(unknown.Visible,"Focus change must clear anonymous departure fence");
var replacement=new CardFixture(); replacement.Set(next,true,a); replacement.TransferToFlight(first.CardInstanceID,a);
Check(replacement.Visible,"Delayed old-card flight must not hide a replacement card");
var fading=new CardFixture(); fading.Set(first,true,a); fading.Set(null,true,a);
Check(fading.Visible && fading.Vanishing,"Non-flight departure must retain native dock crumble");
fading.TransferToFlight(first.CardInstanceID,a);
Check(!fading.Visible && !fading.Vanishing,"Late flight must cancel a source crumble already in progress");
var fx=new FxFixture(); RemoteBoardFocus.Current=a;
var outgoing=new Flight { SourceActor=a, FaceCard=first, Endpoints=(byte)((int)CardFxAnchor.Slot0 | ((int)CardFxAnchor.Discard << 4)) };
fx._owner.Board._cards[0].Set(first,true,a); fx.Apply(outgoing);
Check(!fx._owner.Board._cards[0].Visible,"Production flight orchestration must transfer the source");
RemoteBoardFocus.Current=b; fx._owner.Board._cards[0].ClearFlightTransfer(); fx._owner.Board._cards[0].Set(next,true,b); fx.Apply(outgoing);
Check(fx._owner.Board._cards[0].Visible,"Running A flight must not hide character B");
RemoteBoardFocus.Current=a; fx._owner.Board._cards[0].ClearFlightTransfer(); fx._owner.Board._cards[0].Set(first,true,a); fx.Apply(outgoing);
Check(!fx._owner.Board._cards[0].Visible,"Focus away and back must reassert the retained source identity");
var incoming=new Flight { SourceActor=a,FaceCard=first,Generation=2, Endpoints=(byte)((int)CardFxAnchor.Discard | ((int)CardFxAnchor.Slot0 << 4)) };
fx.Apply(incoming); fx.Apply(outgoing); fx._owner.Board.Landing=first; fx._owner.Board.CompleteFlightLanding(CardFxAnchor.Slot0,a,2,int.MinValue);
Check(fx._owner.Board._cards[0].Visible,"Incoming same-card flight must rearm without an empty snapshot");
fx.Apply(outgoing);
Check(fx._owner.Board._cards[0].Visible,"Older outgoing generation must not reclaim a landed newer card");
fx._owner.Board._cards[0].Blank(); RemoteBoardFocus.Current=b;
fx._owner.Board.CompleteFlightLanding(CardFxAnchor.Slot0,a,2,int.MinValue);
Check(!fx._owner.Board._cards[0].Visible,"Late landing must not recreate source actor on another character");
RemoteBoardFocus.Current=a; RemoteBoardFocus.Exhausted=true;
fx._owner.Board.CompleteFlightLanding(CardFxAnchor.Slot0,a,2,int.MinValue);
Check(!fx._owner.Board._cards[0].Visible,"Late landing must not recreate exhausted actor cards");
RemoteBoardFocus.Exhausted=false;
var acknowledged=new CardFixture(); acknowledged.Set(first,true,a);
acknowledged.TransferToFlight(first.CardInstanceID,a,10); acknowledged.Set(null,true,a);
acknowledged.TransferToFlight(first.CardInstanceID,a,10); acknowledged.Set(first,true,a);
Check(acknowledged.Visible,"Old flight must not recreate its fence after native empty acknowledgement");
acknowledged.TransferToFlight(first.CardInstanceID,a,11); acknowledged.Set(next,true,a);
acknowledged.TransferToFlight(first.CardInstanceID,a,11); acknowledged.Set(null,true,a);
acknowledged.TransferToFlight(first.CardInstanceID,a,11); acknowledged.Set(first,true,a);
Check(acknowledged.Visible,"Old flight must not undo a replacement acknowledgement after that replacement also leaves");
Check(CompactFixture.Advance(true,2,0,0)==0,"Incoming empty Slot0 must not consume existing Slot1 model card");
Check(CompactFixture.Advance(true,3,0,0)==1,"Suppressed occupied Slot0 must consume its own compact model seat");
var home=new HomeFixture(); home._root.transform.position=new System.Numerics.Vector3(10,20,30);
home._root.transform.rotation=Quaternion.AroundZ(MathF.PI/2); home._root.transform.scale=3;
var localHome=new System.Numerics.Vector3(1,2,3); var localRotation=Quaternion.AroundZ(MathF.PI/4);
home.Capture(1,localHome,localRotation,0.63f);
home._cards[1].transform.position=new System.Numerics.Vector3(-8,-9,-10); // still reflowing/hovered
home._cards[1].transform.rotation=Quaternion.identity;
Check(home.TryFlightSeat(2,out var endpoint,out var rotation,out var homeScale),"Recovery must resolve the ordered home seat");
var expectedHome=new System.Numerics.Vector3(4,23,39);
Check(System.Numerics.Vector3.Distance(endpoint,expectedHome)<0.0001f,"Recovery must capture parent-transformed home, not drawn/reflow/pop position");
Check(MathF.Abs(System.Numerics.Quaternion.Dot(rotation.Value,Quaternion.AroundZ(3*MathF.PI/4).Value))>0.99999f,"Recovery must lock parent-times-home rotation, not board or interpolated slab rotation");
Check(MathF.Abs(homeScale-0.63f)<0.00001f,"Recovery must retain native exchange home scale without pop scale");
home._root.transform.position=System.Numerics.Vector3.Zero; home.Capture(1,System.Numerics.Vector3.Zero,Quaternion.identity,1);
Check(System.Numerics.Vector3.Distance(endpoint,expectedHome)<0.0001f,"Captured recovery endpoint must survive later hand/reflow movement");
Check(!home.TryFlightSeat(999,out _,out _,out _),"Unknown recovery card must not borrow a different home");
var arrivals=new ActiveArrivalFixture(); Time.unscaledTime=5f;
Check(arrivals.Hold(1,int.MinValue),"Model-first active arrival retains lost-event grace");
Time.unscaledTime=5.1f;
Check(!arrivals.Hold(1,1),"Exact completed active flight must override future model-first grace immediately");
Check(arrivals.Hold(2,1),"Another card keeps its independent active arrival grace");
arrivals._owner.Flying=true;
Check(arrivals.Hold(1,1),"Another running flight for the same active card retains ownership");
arrivals._owner.Flying=false; Time.unscaledTime=6f;
Check(!arrivals.Hold(2,int.MinValue),"Missing active flight still settles after original bounded grace");
home._shownActor=a; home.Capture(1,localHome,localRotation,0.63f); home._pop[1]=1;
home._cards[1].transform.localPosition=new System.Numerics.Vector3(99,99,99);
home._cards[1].transform.localRotation=Quaternion.identity;
home.CompleteFlightSeat(2,a);
Check(System.Numerics.Vector3.Distance(home._cards[1].transform.localPosition,localHome)<0.0001f,"Landing must expose exact home, not hidden reflow position");
Check(MathF.Abs(System.Numerics.Quaternion.Dot(home._cards[1].transform.localRotation.Value,localRotation.Value))>0.99999f,"Landing must expose exact home rotation");
Check(MathF.Abs(home._cards[1].transform.localScale.X-1.26f)<0.0001f && home._pop[1]==0,"Landing must expose home scale and clear hover pop");
home._cards[1].transform.localPosition=System.Numerics.Vector3.Zero; home.CompleteFlightSeat(2,b);
Check(home._cards[1].transform.localPosition==System.Numerics.Vector3.Zero,"Another actor must not snap this fan's card");
var activeFx=new FxFixture(); RemoteBoardFocus.Current=a;
var oldActiveArrival=new Flight { SourceActor=a, FaceCard=first, ActiveCardId=first.CardInstanceID,Generation=20, Endpoints=(byte)((int)CardFxAnchor.Slot0|((int)CardFxAnchor.Active<<4)) };
activeFx.Apply(oldActiveArrival);
Check(activeFx._owner.OwnsActiveFlight(first.CardInstanceID,a,20),"Drawable active arrival must register its lease before it is shown");
activeFx._owner.TransferCardToFlight(CardFxAnchor.Active,first.CardInstanceID,a,21);
int before=activeFx._owner.Board._active.Refreshes;
activeFx._owner.Board.CompleteFlightLanding(CardFxAnchor.Active,a,20,first.CardInstanceID);
Check(activeFx._owner.Board._active.Refreshes==before,"Old active completion must not reset newer departure fence or grace");
var blockedOldArrival=new Flight { SourceActor=a, FaceCard=first, ActiveCardId=first.CardInstanceID,Generation=19, Endpoints=oldActiveArrival.Endpoints };
activeFx.Apply(blockedOldArrival);
Check(!blockedOldArrival.Active,"Obsolete artwork-delayed active arrival must be rejected before its first drawn frame");
activeFx._owner.Board.BeginActiveFlight(first.CardInstanceID,a,22);
activeFx._owner.Board.CompleteFlightLanding(CardFxAnchor.Active,a,22,first.CardInstanceID);
Check(activeFx._owner.Board._active.Refreshes==before+1,"Latest exact active completion must refresh its landing");
var oldActiveDeparture=new Flight { SourceActor=a, FaceCard=first,Generation=21, Endpoints=(byte)((int)CardFxAnchor.Active|((int)CardFxAnchor.Discard<<4)) };
activeFx.Apply(oldActiveDeparture);
Check(!oldActiveDeparture.Active,"Older delayed active departure must not fly after a newer arrival owns that card");
Console.WriteLine($"Flight timing production policies: {assertions} assertions.");
