<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/GloomhavenVR/WorldUI/Composites/HintMessageOrigins.cs" Link="Production/HintMessageOrigins.cs" />
    <Compile Include="../../src/GloomhavenVR/WorldUI/Modal/ModalFallback.CompositeTransfer.cs" Link="Production/ModalFallback.CompositeTransfer.cs" />
  </ItemGroup>
</Project>
