#!/usr/bin/env python3
"""Bake reviewed Kimodo outputs into deterministic contact-space/retarget samples."""
import argparse,base64,hashlib,json
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
from kimodo.skeleton import SOMASkeleton77

NAMES=['Hips','Spine2','Chest','Neck2','LeftShoulder','RightShoulder','LeftLeg','LeftShin','LeftFoot','RightLeg','RightShin','RightFoot']
CLIPS=[('merchant-count','CountData'),('merchant-return','ReturnData'),('enchantress','SpellData'),('priestess','PrayerData')]
def bake(args):
    s=SOMASkeleton77(); out=['// Generated by scripts/bake-town-motion.py; provenance: TOWN-MOTION-548.md.','namespace GloomhavenVR.WorldUI;','internal static partial class TownServiceMotionClips','{'];report=[]
    for name,field in CLIPS:
        source=args.input/name/'motion.npz';d=np.load(source);p=d['posed_joints'][0];r=d['global_rot_mats'][0];n=len(p);frames=np.zeros((n,63),dtype='<f4');flip=np.diag([1.,1.,-1.])
        for col,joint in enumerate(['LeftHand','RightHand','LeftForeArm','RightForeArm']):
            q=p[:,s.bone_index[joint]].copy();q[:,2]=.65-q[:,2];
            if col<2:q[:,2]-=.045
            frames[:,col*3:col*3+3]=q
        frames[:,12:15]=(p[:,0]-p[0,0])*[1,1,-1]
        for i,joint in enumerate(NAMES):
            j=s.bone_index[joint]; delta=r[:,j]@r[0,j].T;delta=flip@delta@flip
            # A compact actor with independent look-at needs conservative neck/shoulder
            # retargeting. Preserve the generated timing, rather than hard-clamping peaks.
            gain=.15 if joint=='Neck2' else .5 if joint in ['Chest','Spine2'] else .4 if 'Shoulder' in joint else 1.
            frames[:,15+i*4:19+i*4]=Rotation.from_rotvec(Rotation.from_matrix(delta).as_rotvec()*gain).as_quat()
        # Close only the short boundary seam, preserving the generated middle motion.
        # No reverse/ping-pong sampling: time always runs forwards.
        for k in range(8):
            u=(k+1)/8;w=u*u*(3-2*u);idx=n-8+k
            frames[idx,:15]=(1-w)*frames[idx,:15]+w*frames[0,:15]
            for i in range(12):
                a=frames[idx,15+i*4:19+i*4];b=frames[0,15+i*4:19+i*4]
                if np.dot(a,b)<0:b=-b
                q=(1-w)*a+w*b;frames[idx,15+i*4:19+i*4]=q/np.linalg.norm(q)
        if not np.isfinite(frames).all():raise ValueError('Nonfinite bake')
        if np.max(np.abs(frames[:,12:15]))>.15:raise ValueError('Unacceptable root displacement')
        encoded=base64.b64encode(frames.tobytes()).decode();out.append('    private const string '+field+' =')
        for start in range(0,len(encoded),120):out.append('        "'+encoded[start:start+120]+'"'+(';' if start+120>=len(encoded) else ' +'))
        report.append(dict(name=name,frames=n,source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),baked_sha256=hashlib.sha256(frames.tobytes()).hexdigest(),root_range=np.ptp(frames[:,12:15],axis=0).tolist()))
    out.append('}');args.output.write_text('\n'.join(out)+'\n');args.report.write_text(json.dumps(report,indent=2)+'\n')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--input',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--report',type=Path,required=True);bake(p.parse_args())
