"""Only previewed owned caches are removed; delivered content/signing survive."""
import errno
import hashlib
import json
import os
from pathlib import Path, PureWindowsPath
import sys
import tempfile
import unittest
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/quest-wizard"))
import cleanup
import state


def hashed(raw): return hashlib.sha256(raw).hexdigest()


class CleanupTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(); self.addCleanup(temporary.cleanup)
        self.temp = Path(temporary.name); self.root = self.temp / "owned"
        self.store = state.Store(self.root); self.build = self.root / "build"; self.build.mkdir()
        cleanup._plans.clear(); self.addCleanup(cleanup._plans.clear)
        self.original = self.temp / "OriginalGame"; self.original.mkdir()
        (self.original / "leave-alone.bin").write_bytes(b"owned original")

    def file(self, relative, raw=b"owned generated bytes"):
        path = self.build / relative; path.parent.mkdir(parents=True, exist_ok=True); path.write_bytes(raw)
        return {"path": relative, "size": len(raw), "sha256": hashed(raw)}

    def snapshots(self):
        rows = [{"path": name, "size": len(name.encode()), "sha256": hashed(name.encode())}
                for name in ("Managed/Apparance.Net.dll", "app.info")]
        ordered = sorted(rows, key=lambda row: row["path"])
        wrong = sorted(rows, key=lambda row: PureWindowsPath(row["path"]))
        self.correct = state.value_hash({"files": ordered}); self.wrong = state.value_hash({"files": wrong})
        self.assertNotEqual(self.correct, self.wrong)
        for key, current in ((self.correct, ordered), (self.wrong, wrong)):
            for row in current: self.file("inputs/game/" + key + "/" + row["path"], row["path"].encode())
            state.atomic_json(self.build / "inputs/game" / key / ".snapshot.json", {"schema": 1, "files": current})
        mod_rows = [{"path": "tools/quest-builder/storage.py", "size": 3, "sha256": hashed(b"mod")}]
        value = {"schema": 1, "target": "game", "recipe": "fixture", "game": {"key": self.wrong, "files": wrong},
                 "mod": {"key": state.value_hash({"files": mod_rows}), "files": mod_rows}}
        value["inputKey"] = state.value_hash(value)
        self.manifest = self.build / "manifests" / (value["inputKey"] + ".json")
        state.atomic_json(self.manifest, value)
        return ordered, wrong

    def raw_recovery(self, wrong, *, corrupt=False):
        receipt = self.build / "inputs/game" / self.wrong / ".snapshot.json"
        rows = [{"path": row["path"], "bytes": row["size"], "sha256": row["sha256"]} for row in wrong]
        rows.append({"path": ".snapshot.json", "bytes": receipt.stat().st_size, "sha256": hashed(receipt.read_bytes())})
        value = {"schema": 1, "sourceInventory": rows,
                 "sourceFingerprint": hashed(json.dumps(rows, sort_keys=True, separators=(",", ":")).encode())}
        if corrupt: value["sourceFingerprint"] = "0" * 64
        self.raw = self.build / "cache/full-original-recovery" / ("c" * 64)
        state.atomic_json(self.raw / "original-source.json", value)
        self.file(self.raw.relative_to(self.build).as_posix() + "/RecoveredProject/asset.bin")
        return self.raw

    def success(self):
        key = "a" * 64
        apk = self.file("builds/" + key + "/GloomhavenVR-Quest.apk", b"signed fixture APK")
        bank = self.file("builds/" + key + "/GloomhavenVR-Quest-content.zip", b"complete fixture bank")
        details = {"isDiagnostic": False, "apkSha256": apk["sha256"], "contentFiles": [bank]}
        receipt = "receipts/build/" + key + ".json"
        state.atomic_json(self.build / receipt, {"schema": 1, "stage": "build", "key": key,
                          "outputs": [apk, bank], "details": details})
        state.atomic_json(self.build / "latest-build.json", {"schema": 1, "apk": apk["path"], "receipt": receipt, "details": details})
        return apk, bank

    def test_duplicate_original_snapshot_and_matching_raw_stage_are_removed(self):
        ordered, wrong = self.snapshots(); raw = self.raw_recovery(wrong)
        derived = self.build / "cache/recovery" / ("d" * 64)
        state.atomic_json(derived / "stage-owner.json", {"schema": 1, "owner": "Quest recovered Campaign stage",
                          "key": derived.name, "gameKey": self.wrong})
        self.file(derived.relative_to(self.build).as_posix() + "/project/asset.bin")
        (self.build / "cache/full-original-recovery" / ("e" * 64)).mkdir()
        self.file("cache/full-original-recovery/" + "e" * 64 + "/unknown.bin")
        events = []; preview = cleanup.plan(self.root, progress=events.append)
        self.assertTrue(preview["eligible"]); self.assertTrue(preview["exact"]); self.assertEqual(len(preview["paths"]), 3)
        result = cleanup.execute(self.root, preview, events.append)
        self.assertEqual(result["freedBytes"], preview["bytes"]); self.assertEqual(result["deletedFiles"], preview["files"])
        self.assertFalse((self.build / "inputs/game" / self.wrong).exists()); self.assertFalse(raw.exists()); self.assertFalse(derived.exists())
        self.assertTrue((self.build / "inputs/game" / self.correct).is_dir())
        self.assertTrue((self.build / "cache/full-original-recovery" / ("e" * 64) / "unknown.bin").is_file())
        self.assertEqual(result["invalidatedStages"], [])
        self.assertTrue(events); self.assertEqual(events[-1]["done"], preview["files"])

    def test_correct_original_snapshot_is_required(self):
        self.snapshots(); (self.build / "inputs/game" / self.correct / ".snapshot.json").unlink()
        self.assertFalse(cleanup.plan(self.root)["eligible"])
        self.assertTrue((self.build / "inputs/game" / self.wrong).exists())

    def test_corrupt_manifest_does_not_authorize_duplicate_cleanup(self):
        self.snapshots(); value = json.loads(self.manifest.read_text()); value["recipe"] = "changed"
        state.atomic_json(self.manifest, value)
        self.assertFalse(cleanup.plan(self.root)["eligible"])

    def test_corrupt_raw_owner_is_retained(self):
        _, wrong = self.snapshots(); raw = self.raw_recovery(wrong, corrupt=True)
        preview = cleanup.plan(self.root); cleanup.execute(self.root, preview)
        self.assertTrue(raw.exists())

    def test_surplus_snapshot_data_is_retained(self):
        self.snapshots(); self.file("inputs/game/" + self.wrong + "/unknown.bin")
        self.assertFalse(cleanup.plan(self.root)["eligible"])

    def test_changed_canonical_receipt_invalidates_preview_before_any_delete(self):
        self.snapshots(); preview = cleanup.plan(self.root)
        canonical = self.build / "inputs/game" / self.correct / ".snapshot.json"
        canonical.write_bytes(canonical.read_bytes() + b" ")
        with self.assertRaises(state.WizardError): cleanup.execute(self.root, preview)
        self.assertTrue((self.build / "inputs/game" / self.wrong).exists())

    def test_added_file_or_replaced_tree_invalidates_preview(self):
        for change in ("added", "replaced"):
            with self.subTest(change=change):
                self.success(); self.file("cache/generated.bin"); preview = cleanup.plan(self.root, "build-cache")
                if change == "added": self.file("cache/new.bin")
                else:
                    cache = self.build / "cache"; cache.rename(self.build / "retained-cache"); cache.mkdir(); self.file("cache/generated.bin")
                with self.assertRaises(state.WizardError): cleanup.execute(self.root, preview)
                self.assertTrue((self.build / "cache").exists())

    def test_client_paths_or_modified_plan_never_authorize_other_deletion(self):
        self.success(); self.file("cache/generated.bin"); preview = cleanup.plan(self.root, "build-cache")
        preview["paths"] = [{"path": "../OriginalGame", "bytes": 1}]
        cleanup.execute(self.root, preview)
        self.assertEqual((self.original / "leave-alone.bin").read_bytes(), b"owned original")
        with self.assertRaises(state.WizardError): cleanup.execute(self.root, {"id": "invented", "paths": []})

    def test_build_cache_removes_only_intermediates_and_preserves_delivery_signing(self):
        apk, bank = self.success()
        for folder in ("cache", "projects", "inputs"): self.file(folder + "/generated.bin")
        for folder in ("signing", "tool-cache", "logs", "updates", "manifests"): self.file(folder + "/retained.bin")
        preview = cleanup.plan(self.root, "build-cache"); result = cleanup.execute(self.root, preview)
        self.assertEqual(result["invalidatedStages"], ["inspect", "build"])
        for folder in ("cache", "projects", "inputs"): self.assertFalse((self.build / folder).exists())
        for folder in ("signing", "tool-cache", "logs", "updates", "manifests"): self.assertTrue((self.build / folder / "retained.bin").exists())
        self.assertTrue((self.build / apk["path"]).exists()); self.assertTrue((self.build / bank["path"]).exists())
        self.assertTrue((self.build / "latest-build.json").exists()); self.assertTrue((self.original / "leave-alone.bin").exists())

    def test_cleanup_never_reads_original_assets_apk_or_content_bank(self):
        self.snapshots(); apk, bank = self.success(); self.file("cache/generated.bin")
        original_open = Path.open
        def opening(path, mode="r", *args, **kwargs):
            if mode == "rb" and path.suffix != ".json": raise AssertionError("cleanup asset reread: " + str(path))
            return original_open(path, mode, *args, **kwargs)
        with mock.patch.object(Path, "open", opening):
            preview = cleanup.plan(self.root, "build-cache"); cleanup.execute(self.root, preview)

    def test_unsuccessful_missing_bank_or_changed_metadata_keeps_caches(self):
        for failure in ("missing", "size", "receipt", "diagnostic"):
            with self.subTest(failure=failure):
                apk, bank = self.success(); self.file("cache/generated.bin")
                if failure == "missing": (self.build / bank["path"]).unlink()
                elif failure == "size": (self.build / apk["path"]).write_bytes(b"changed size")
                else:
                    pointer = self.build / "latest-build.json"; value = json.loads(pointer.read_text())
                    if failure == "receipt": value["receipt"] = "../private.json"
                    else: value["details"]["isDiagnostic"] = True
                    state.atomic_json(pointer, value)
                with self.assertRaises(state.WizardError) as error: cleanup.plan(self.root, "build-cache")
                self.assertEqual(error.exception.code, "cleanup_no_completed_build")
                self.assertTrue((self.build / "cache/generated.bin").exists())

    def test_linked_directory_and_junction_style_metadata_are_never_deleted(self):
        self.success(); self.file("cache/generated.bin")
        (self.build / "cache" / "linked").symlink_to(self.original, target_is_directory=True)
        preview = cleanup.plan(self.root, "build-cache")
        self.assertFalse(preview["eligible"]); self.assertTrue(preview["skipped"])
        self.assertTrue((self.original / "leave-alone.bin").exists())

    def test_workspace_owner_or_other_workspace_preview_is_rejected(self):
        self.success(); self.file("cache/generated.bin"); preview = cleanup.plan(self.root, "build-cache")
        other = self.temp / "another"; state.Store(other)
        with self.assertRaises(state.WizardError): cleanup.execute(other, preview)
        state.atomic_json(self.root / "wizard-owner.json", {"schema": 1, "owner": "different"})
        with self.assertRaises(state.WizardError): cleanup.plan(self.root)

    def test_active_builder_or_wizard_cannot_be_cleaned(self):
        self.snapshots()
        with cleanup._helper().output_lock(self.build):
            with self.assertRaises(state.WizardError) as error: cleanup.plan(self.root)
        self.assertEqual(error.exception.code, "cleanup_busy")
        with state.file_lock(self.root / "run.lock"):
            with self.assertRaises(state.WizardError) as error: cleanup.plan(self.root)
        self.assertEqual(error.exception.code, "already_running")

    def test_full_drive_uses_existing_same_kernel_guard_without_status_write(self):
        self.snapshots()
        with cleanup._helper().output_lock(self.build): pass
        failure = OSError(errno.ENOSPC, "No space left")
        with mock.patch.object(cleanup._helper(), "write_json", side_effect=failure):
            preview = cleanup.plan(self.root); result = cleanup.execute(self.root, preview)
        self.assertGreater(result["freedBytes"], 0)
        self.assertTrue((self.build / ".builder.guard").exists())

    def test_enospc_from_cleanup_body_is_not_retried(self):
        self.snapshots(); preview = cleanup.plan(self.root)
        original = cleanup._scan; calls = []
        def scan(*args, **kwargs):
            calls.append(args[0]); raise OSError(errno.ENOSPC, "failure in cleanup body")
        with mock.patch.object(cleanup, "_scan", side_effect=scan):
            with self.assertRaises(OSError): cleanup.execute(self.root, preview)
        self.assertEqual(len(calls), 1)
        self.assertTrue((self.build / "inputs/game" / self.wrong).exists())

    def test_valid_closed_apk_update_can_remove_cache_and_keeps_original_bank(self):
        _, bank = self.success(); key = "b" * 64
        apk = self.file("updates/" + key + "/GloomhavenVR-Quest.apk", b"signed updated APK")
        details = {"isDiagnostic": False, "apkSha256": apk["sha256"], "contentFiles": [],
                   "retainedGameContent": True, "inputKey": "f" * 64}
        report = {"schema": 1, "scope": "APK update", "buildResult": "Succeeded", **details}
        state.atomic_json(self.build / (apk["path"] + ".build.json"), report)
        raw = (self.build / (apk["path"] + ".build.json")).read_bytes()
        report_row = {"path": apk["path"] + ".build.json", "size": len(raw), "sha256": hashed(raw)}
        receipt = "receipts/build/" + key + ".json"
        state.atomic_json(self.build / receipt, {"schema": 1, "stage": "build", "key": key, "outputs": [apk, report_row], "details": details})
        state.atomic_json(self.build / "latest-build.json", {"schema": 1, "apk": apk["path"], "receipt": receipt, "details": details})
        self.file("cache/generated.bin")
        preview = cleanup.plan(self.root, "build-cache"); cleanup.execute(self.root, preview)
        self.assertTrue((self.build / apk["path"]).exists()); self.assertTrue((self.build / bank["path"]).exists())

    def test_private_signing_files_within_a_cache_are_preserved(self):
        self.success(); self.file("cache/generated.bin"); self.file("cache/personal.keystore", b"private identity")
        preview = cleanup.plan(self.root, "build-cache")
        self.assertFalse(preview["eligible"])
        self.assertEqual(preview["skipped"][0]["reason"], "cleanup_signing_path")
        self.assertEqual((self.build / "cache/personal.keystore").read_bytes(), b"private identity")

    def test_preview_expiry_single_use_and_same_size_edit_preserve_targets(self):
        self.success(); self.file("cache/generated.bin"); preview = cleanup.plan(self.root, "build-cache")
        with mock.patch.object(cleanup.time, "monotonic", return_value=time_value(cleanup, preview) + cleanup.PREVIEW_SECONDS + 1):
            with self.assertRaises(state.WizardError): cleanup.execute(self.root, preview)
        self.assertTrue((self.build / "cache/generated.bin").exists())
        preview = cleanup.plan(self.root, "build-cache")
        path = self.build / "cache/generated.bin"; previous = path.stat(); path.write_bytes(b"changed generated raw")
        self.assertEqual(path.stat().st_size, previous.st_size)
        os.utime(path, ns=(previous.st_atime_ns, previous.st_mtime_ns))
        with self.assertRaises(state.WizardError): cleanup.execute(self.root, preview)
        self.assertTrue(path.exists())
        with self.assertRaises(state.WizardError): cleanup.execute(self.root, preview)

    def test_unsafe_relative_paths_are_rejected_even_with_self_consistent_owner(self):
        for path in ("../OriginalGame/leave-alone.bin", "C:/OriginalGame/a.bin", "folder\\a.bin", "/absolute.bin"):
            with self.subTest(path=path), self.assertRaises(state.WizardError):
                cleanup._rows([{"path": path, "size": 1, "sha256": "a" * 64}])

    def test_replaced_canonical_directory_and_added_link_stop_before_deletion(self):
        self.snapshots(); preview = cleanup.plan(self.root)
        correct = self.build / "inputs/game" / self.correct
        correct.rename(correct.with_name("retained-canonical")); correct.mkdir()
        with self.assertRaises(state.WizardError): cleanup.execute(self.root, preview)
        self.assertTrue((self.build / "inputs/game" / self.wrong).exists())

    def test_file_links_and_mocked_junction_reparse_attribute_are_preserved(self):
        self.success(); self.file("cache/generated.bin")
        leaf = self.build / "cache/linked.bin"; leaf.symlink_to(self.original / "leave-alone.bin")
        self.assertFalse(cleanup.plan(self.root, "build-cache")["eligible"])
        leaf.unlink()
        old_stamp = cleanup._stamp
        def stamp(path):
            if Path(path) == self.build / "cache": raise state.WizardError("cleanup_linked_path", "Windows reparse directory")
            return old_stamp(path)
        with mock.patch.object(cleanup, "_stamp", side_effect=stamp):
            self.assertFalse(cleanup.plan(self.root, "build-cache")["eligible"])
        self.assertTrue((self.original / "leave-alone.bin").exists())

    def test_session_invalidation_is_done_while_run_lock_is_held(self):
        self.success(); self.file("cache/generated.bin")
        running = self.store.create({"mode": "build"}); running["status"] = "failed"
        for row in running["stages"]:
            if row["id"] in ("inspect", "build"):
                row.update(status="failed", details={"old": True}, progressPlan={"old": True}, progressWorkKey="old")
                state.atomic_json(self.store.receipt(running["session"], row["id"]), {"schema": 1})
        self.store.save(running)
        success = self.store.create({"mode": "build"}); success["status"] = "complete"
        for row in success["stages"]: row["status"] = "complete"
        self.store.save(success)
        original = cleanup._invalidate
        def invalidate(root):
            with self.assertRaises(state.WizardError):
                with state.file_lock(root / "run.lock"): pass
            return original(root)
        preview = cleanup.plan(self.root, "build-cache")
        with mock.patch.object(cleanup, "_invalidate", side_effect=invalidate): result = cleanup.execute(self.root, preview)
        current = self.store.load(running["session"])
        self.assertEqual(current["status"], "ready")
        for row in current["stages"]:
            if row["id"] in ("inspect", "build"):
                self.assertEqual(row["status"], "pending"); self.assertEqual(row["details"], {})
                self.assertEqual(row["progressPlan"]["percent"], 0)
                self.assertEqual(row["progressPlan"]["completed"], [])
                self.assertFalse(self.store.receipt(running["session"], row["id"]).exists())
        completed = self.store.load(success["session"])
        self.assertEqual(completed["status"], "complete"); self.assertTrue(completed["cacheCleaned"])
        self.assertEqual(set(result["sessionsReset"]), {running["session"], success["session"]})


def time_value(module, preview): return module._plans[preview["id"]]["created"]


if __name__ == "__main__": unittest.main()
